### ISSUE TITLE
Support OneOf on Input Objects

### ISSUE THREAD

**Issue by Tehnix** [sangria-graphql/sangria#1068]
It seems `oneOf` has largely been accepted, and many GraphQL libraries have either started implementation or already rolled it out https://github.com/graphql/graphql-spec/pull/825.

Is there any interest in Sangria supporting this, and would there be any technical blockers for it?

At $work we have had several cases where support for this would have made the resulting API better and more intuitive.

For inspiration, there's ongoing work in caliban here https://github.com/ghostdogpr/caliban/pull/1846.

**Comment by yanns** [comment]
Yes, this can be interesting.
I don't think I'll have time to work on it in the next weeks though.

**Comment by yanns** [comment]
released in https://github.com/sangria-graphql/sangria/releases/tag/v4.2.0
