### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by eugkhp** [sangria-graphql/sangria#1078]
The documentation website shows some weird info  https://sangria-graphql.org/
<img width="1352" alt="image" src="https://github.com/sangria-graphql/sangria/assets/25910599/3a0bc815-e814-4503-9198-2cceb36d6aad">

**Comment by yanns** [comment]
https://github.com/sangria-graphql/sangria-graphql.github.io/issues/74

the new website is https://sangria-graphql.github.io/
