### ISSUE TITLE
Ability to identify response status code

### ISSUE THREAD

**Issue by OlegIlyenko** [sangria-graphql/sangria#109]
At the moment all requests result in 200 status code. Ideally it should be 400 for invalid queries.

**Comment by jverghese** [comment]
:+1: Also, would be great to add support for response codes like 401 if query isn't authorized.

**Comment by OlegIlyenko** [comment]
This feature should propagate errors that happen before actual query execution (validation, query reducers) up to the user. This will make it easy to map an error to a status code.
