### ISSUE TITLE
Support for @cacheControl

### ISSUE THREAD

**Issue by zvuki** [sangria-graphql/sangria#1124]
I wonder if there is any appetite for Apollo's `@cacheControl` https://www.apollographql.com/docs/apollo-server/performance/caching/ support in Sangria in the community.

**Comment by yanns** [comment]
`@cacheControl` is not a standard GraphQL directive.
Therefore it cannot be added to the sangria standard library.

What you could do instead is to create a library based on sangria that would provide the directive and some support for caching.
If you create such library, we could add it the the ecosystem.

**Comment by yanns** [comment]
I'm closing this issue for now. Feel free to open it again if you have some news.
