### ISSUE TITLE
Provide tooling to generate `schema.json` for other libraries and tools (like babel)

### ISSUE THREAD

**Issue by OlegIlyenko** [sangria-graphql/sangria#129]
Maybe it's possible to create an SBT plugin that executes an introspection query against application's schema?

**Comment by YasserKaddour** [comment]
HI Oleg,
This is my attempt sangria-graphql/sangria-relay-playground/ff4d0cd to create an sbt task that generate schema.json at every reload, it's not the [proper sbt way to generate ressources](http://stackoverflow.com/a/23416018/3354657) but it works.

To create a proper plugin Sangria need to be cross compiled with Scala 2.10, I tried to that but I had errors in DeriveObjectTypeMacro.scala. Maybe you could do it.

Cheers

**Comment by OlegIlyenko** [comment]
Cool, thanks a lot for looking into it! I haven't anticipated that scala 2.10 would be required. This requirement probably would be dropped in SBT 1.0 (I hope at least).

I will definitely look at it in more detail a bit later

**Comment by YasserKaddour** [comment]
I think we still have to wait for sbt 1.0 ^^

**Comment by OlegIlyenko** [comment]
Just looked closer at the `schema.json` generation that you have implemented. It looks great! The "proper" way will not really work anyway because schema is defined in the application classpath. Proposed solution (in SO issue you linked) moves source generator out of the application in the SBT project where it will not be able to access application-specific schema definition classes, as far as I can tell.

Maybe another idea would be to expand on this solution and extract `generateSchema` task (the one that uses `fullRunTask`) in SBT plugin which will also automatically generate the `GenerateSchema` object in the classpath based on some setting that defines the location of GraphQL schema. For instance:

```scala
graphqlSchema := "models.SchemaDefinition.schema"
```

It may (optionally) also provide an ability to override the whole schema generation object and not only the schema location with some other setting.

WDYT?

I also left one comment here: https://github.com/sangria-graphql/sangria-relay-playground/commit/ea41f6b702e9d618d20ebf0715f8676cf3009ea9#commitcomment-17314106

**Comment by YasserKaddour** [comment]
I think expanding on this solution would be easier, I don't know what exactly could be done in an sbt-plugin, I am in the middle of the book "sbt in Action" by Josh Suereth and Matthew Farwell, and I was just getting to the plugin part.

And yes `Await` is better, thanks for spotting that.

**Comment by OlegIlyenko** [comment]
:+1: It's on my reading list as well :)

**Comment by YasserKaddour** [comment]
It's quite a good book :)

**Comment by nelanka** [comment]
The Amazon reviews on that book make it seem terrible. Is it really as bad as they say?

**Comment by jonas** [comment]
I've implemented this idea in https://github.com/mediative/sangria-codegen/pull/7. Instead of `schema.json` it generates a `schema.graphql` file.

The following [`build.sbt`](https://github.com/mediative/sangria-codegen/blob/54dce801bc6b789fb9cdb5efb01a2e577d8be452/sbt-sangria-codegen/src/sbt-test/sangria-codegen/generate-schema-and-code/build.sbt) shows how a `schema.graphql` file is first generated from which client code is then generated.

**Comment by OlegIlyenko** [comment]
Closing in favour of tooling provided by https://github.com/mediative/sangria-codegen and  https://github.com/muuki88/sbt-graphql
