### ISSUE TITLE
Question: Handling errors within a ListType

### ISSUE THREAD

**Issue by thisismana** [sangria-graphql/sangria#134]
Suppose you have a Field of type `ListType[U]` with a parameter of type `ListInputType[T]` and the context only allows resolving one at a time `f(x: T) -> Future[U]`.

How would you write the resolve function that allows serving the valid entries (as `data` in the response) and adding those that failed to the `error` field in the response.

So far, I managed to fail the whole request by invoking `Future.sequence()` or filter out the failed ones but then those would not appear in the `error` node.

**Comment by OlegIlyenko** [comment]
Indeed, at the moment only a single exception is supported. You can either throw it or return it via failed `Future` or `Try` from a `resolve` function. 

One thing you can do is to create an "umbrella" exception which will contain a list of other exceptions or  other types of errors. They in [custom `ExceptionHandler`](http://sangria-graphql.org/learn/#custom-exceptionhandler) you can provide a custom rendering logic for this exceptions (you can also add fields in there). This will still result in one error entry in the response, but you have a bit more flexibility in there.

I should be possible to introduce a way to report multiple errors in single field which translates in multiple error entries in the response (sangria internally uses something like this for different types of errors, like validation errors). But before we do it I would love to understand the actual use-case for it. I saw this feature request appearing in graphql-js many times and in most cases the use-case was an application level error propagation (by this I mean errors which are part of the normal client-server communication flow. For instance, a form validation errors). As far as a saw, it is discouraged to use GraphQL errors for these types of use-cases: they meant to be used for truly exceptional situations, when error means that either client or server developer have make a mistake, introduced a bug, or something along these lines.

**Comment by OlegIlyenko** [comment]
I was thinking about this and I think there there are valid use-cases for this. At the moment it is not possible to express a partial results, so I decided to add them: https://github.com/sangria-graphql/sangria/issues/140

I would appreciate if you could look at it and give your opinion on this feature (and whether it helps in your particular case)

**Comment by OlegIlyenko** [comment]
Here is a test case that demonstrates this feature: https://github.com/sangria-graphql/sangria/blob/76f5d60ddb9721852036e8ccde616e00674b2720/src/test/scala/sangria/execution/ExecutorSpec.scala#L656-L656

**Comment by OlegIlyenko** [comment]
Closing in favor of #140. Please feel free to reopen if you think that it doesn't really solve this issue, or you would like to discuss it a bit more.

**Comment by santilytics** [comment]
I apologize before hand for lack of clarity as I've been working with Scala for about a week now. I've been using your graphql-gateway project and I don't have enough control over Sangria to control errors the way I'd like to.
As it stands right now, I'm able to use my server as a proxy for another graphql server. The only caveat is that I'm not relaying the errors even though I'm receiving them in my server.

So far a change that has helped me is removing the `map` in the request which extracts the value as such:
```scala
c.ctx.request(schema, query, c.ctx.queryVars, c.astFields.head.outputName)
            .map(value => ResolverBasedAstSchemaBuilder.extractValue[Json](c.field.fieldType, Some(value))
```
This includes the error but the message doesn't get parsed correctly. It instead displays internal server errors.

For future reference, this looked like an appropriate place to place this question but would it be preferred as an issue in the graphql-gateway project?
