### ISSUE TITLE
[question] ResultMarshaller: None as null

### ISSUE THREAD

**Issue by lvicentesanchez** [sangria-graphql/sangria#144]
I'm a bit curious about the reasoning behind emitting a `null` when an optional field is `None`; I would have expected the field to be removed from the output in such a case.

**Comment by OlegIlyenko** [comment]
It's a part of the GraphQL spec. As far as i remember it's described in the execution part of the spec: http://facebook.github.io/graphql/#sec-Evaluating-a-grouped-field-set

**Comment by lvicentesanchez** [comment]
Thanks! That makes sense now :)
