### ISSUE TITLE
Updated context propagated only to siblings

### ISSUE THREAD

**Issue by schickling** [sangria-graphql/sangria#145]
It looks like the updated context is propagated only to siblings, but not to children in case of a (Relay) mutation.

**Comment by OlegIlyenko** [comment]
Thanks a lot for finding and reporting this bug! Bugfix will come in the next version. Meanwhile I published a snapshot build. You can use it in your project like this:

```scala
resolvers += "Sonatype snapshots" at "https://oss.sonatype.org/content/repositories/snapshots/"
libraryDependencies += "org.sangria-graphql" %% "sangria" % "0.7.1-SNAPSHOT"
```

**Comment by schickling** [comment]
Thank you for fixing this so quickly. Great work!
