### ISSUE TITLE
Sangria derive macros seem to interfere with incremental compilation

### ISSUE THREAD

**Issue by JohnCohorn** [sangria-graphql/sangria#150]
Quite often when compiling via sbt without a clean myself as well as colleagues run into this error:

```
[error] Unknown type: (marginChar: Char)String <and> ()String, (marginChar: Char)String <and> ()String [class scala.reflect.internal.Types$OverloadedType, class scala.reflect.internal.Types$OverloadedType] TypeRef? false
scala.reflect.internal.FatalError: Unknown type: (marginChar: Char)String <and> ()String, (marginChar: Char)String <and> ()String [class scala.reflect.internal.Types$OverloadedType, class scala.reflect.internal.Types$OverloadedType] TypeRef? false
```

This _only_ happens after modifying files containing containing a large number of sangria.macros.derive.\* macro usages. Even adding a single new line to the file causes the failure and rerunning the compile after a clean always succeeds. I'm not familiar enough with Scala macros' implementation to be sure if this might be due to sbt/scalac bugs/limitations w.r.t. macros or if this might possibly be a bug in Sangria's derive\* macros that triggers this.

I haven't been able to produce the same problem yet in a cut down test project, but I've attached most of the sbt output in hopes something might be evident from that.

[Sangria_Macro_Inc_Compile_Stacktrace.txt](https://github.com/sangria-graphql/sangria/files/366751/Sangria_Macro_Inc_Compile_Stacktrace.txt)

Versions:
Scala: 2.11.8
SBT: 0.13.9
Java: 1.8.0_91

Sangria Imports in a problem file:
import sangria.macros.derive._
import sangria.schema._
import sangria.marshalling.playJson._
import sangria.marshalling._

Thanks for any help!

**Comment by OlegIlyenko** [comment]
Thanks a lot for a detailed report. It looks like a compiler issue at the first glance. I will look at it in more detail as soon as i get an opportunity.

**Comment by JohnCohorn** [comment]
Thanks for taking a look. You're probably right that it's an sbt or scalac issue.

I did notice a couple of other things though. If I isolate all the macro usages into a single Foo.scala file containing nothing else this still occurs. If I touch Foo.scala or a companion object of a case class the macros reference(which also causes Foo.scala's inclusion in recompilation) I get the error. This is only the case for  deriveObjectType and deriveInputObjectType usages though. If I touch the companion object of an Enumeration referenced by deriveEnumType I do not get the error. So I believe the problem is triggered by something particular to the deriveObjectType and deriveInputObjectType macros.

**Comment by JohnCohorn** [comment]
Oddly the problem seems to have gone away after some refactoring. Before the schema types for several enumerations, object types, and input object types were defined alongside one another in a single Schema.scala file. I moved the schema derivations to the companion object of the case classes they're for like this:

```
object Character {
  implicit val playFormat: Format[Character] = Json.format[Character]
  implicit val characterType = deriveObjectType[Unit, Character]()
  implicit val characterInputType = deriveInputObjectType[Character]()
}
```

I also:
- changed several case classes from defining their own FromInput using CoercedScalaResultMarshaller to rely on Play's macro based formats instead
- Began using my own simple helper to generate a schema for Scala Enumerations using reflection and placing it on the enum's companion object. I had trouble with deriveEnumType, but only when used in an Enumeration's companion object.

That's really all that was changed in the commit that fixed our compile. I'm not sure if this helps much in explaining the root cause of the problem, but wanted to share in case others run into a similar problem.

**Comment by OlegIlyenko** [comment]
Nice! Thanks for sharing all this info! I'm sure it would be helpful for analysis.

> I had trouble with deriveEnumType, but only when used in an Enumeration's companion object.

Can you share more details about issues you faced with it? Maybe I can help?

**Comment by JohnCohorn** [comment]
Sure! So if I create a new enum which isn't referenced anywhere else and use deriveEnumType like this:

```
package com.$COMPANY.$PROJECT.planning.model

import play.api.libs.json.{Format, Reads, Writes}
import sangria.macros.derive.deriveEnumType
import sangria.schema.EnumType

object ValName extends Enumeration {
  type ValName = Value
  val FOO, BAR, BAZ = Value

  implicit val playFormat = Format(Reads.enumNameReads(ValName), Writes.enumNameWrites[ValName.type])
  implicit val valNameType = deriveEnumType[ValName.ValName]()
}
```

I get this error when compiling:

```
[error] /Users/jcohorn/gitrepos/$PROJECT/src/main/scala/com/$COMPANY/$PROJECT/planning/model/ValName.scala:11: recursive value valNameType needs type
[error]   implicit val valNameType = deriveEnumType[ValName.ValName]()
```

If I add an explicit type annotation as suggested by the error message:

`implicit val valNameType: EnumType[ValName.ValName] = deriveEnumType[ValName.ValName]()`

The error message becomes this:

```
[error] /Users/jcohorn/gitrepos/$PROJECT/src/main/scala/com/$COMPANY/$PROJECT/planning/model/ValName.scala:12: type mismatch;
[error]  found   : sangria.schema.EnumType[com.$COMPANY.$PROJECT.planning.model.ValName.ValName]
[error]     (which expands to)  sangria.schema.EnumType[com.$COMPANY.$PROJECT.planning.model.ValName.Value]
[error]  required: com.$COMPANY.$PROJECT.planning.model.ValName.ValName
[error]     (which expands to)  com.$COMPANY.$PROJECT.planning.model.ValName.Value
[error]   implicit val valNameType: EnumType[ValName.ValName] = deriveEnumType[ValName.ValName]()
```

I tried several permutations of how to specify the desired types and couldn't seem to get it to work out, always getting compile errors similar to the above. If I use the deriveEnumType macro to derive the type somewhere other than within the ValName object I do not seem to get errors, but I'd prefer to place it there to remain consistent with how the other schema objects are defined.

**Comment by OlegIlyenko** [comment]
Sorry for keeping you waiting. It was bug in the `deriveEnumType` macro: #151. I fixed it now, so you should be define an implicit type in the `Enumeration` itself (after it's released):

https://github.com/sangria-graphql/sangria/blob/master/src/test/scala/test/testMacroModelWithCompanions.scala#L35-L40

**Comment by JohnCohorn** [comment]
Awesome, THANK YOU! We love using Sangria so far and are starting to use it more and more so these little fixes add up to make a big difference :)

**Comment by OlegIlyenko** [comment]
After implementing a cross-compilation to scala 2.12, I noticed that macro compilation became more stable and predictable. 

Since some of the issues, described here, are addressed, I will close close the issue for now, but if this strange compiler behavior will occur again, I would suggest to repoen it, or (even better create) a new issue and reference this one (so that we can keep track of them)
