### ISSUE TITLE
Can't find suitable GraphQL output type for Float

### ISSUE THREAD

**Issue by sumeetn** [sangria-graphql/sangria#175]
I am getting the error 
Can't find suitable GraphQL output type for Float. If you have defined it already, please consider making it implicit and ensure that it's available in the scope.
 `implicit val PersonType = deriveObjectType[Unit, Person]()`

I am getting this error in my complex project, here I have tried to simplify the problem so that it can be reproduced. I understand that Sangria supports Float , interestingly making percent datatype as Double works but for me float is must.

Seems like something I am not doing right here, can you please help me in solving this

```
import sangria.execution.Executor
import sangria.macros._
import sangria.macros.derive._
import sangria.schema.{Context, Schema}
import scala.concurrent.Await
import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.duration._

case class Person(id: String, name: String, percent:Float)

class PersonContext {
  val queries: PersonQueries = new PersonQueries
}


class PersonQueries {
  @GraphQLField def persons(ctx: Context[PersonContext, Unit])(personId: Option[String]): Seq[Person] = {
    Seq(Person("1", "Tom",50), Person("2", "Hardy",60.5f))
  }
}


object GraphqlTest2 extends App {
  implicit val PersonType = deriveObjectType[Unit, Person]()
  val PersonQueriesType = deriveContextObjectType[PersonContext, PersonQueries, Unit](_.queries)
  val PersonSchema = Schema(PersonQueriesType)
  val document = graphql"""{ persons {name,percent} }"""
  val ctx = new PersonContext()
  Await.result(Executor.execute(PersonSchema, queryAst = document, userContext = ctx).map(res => println("*** " + res)), 10.seconds)
}

```

**Comment by OlegIlyenko** [comment]
The actual scala `Float` values are not supported out-of-the-box (by sangria and GraphQL), Sangria supports only `Double` and `BigDecimal`. 

You can create your own custom scalar value, though. There is how the `Double` is implemented:

https://github.com/sangria-graphql/sangria/blob/master/src/main/scala/sangria/schema/package.scala#L64-L93

 It would be something very similar for `Float`, though you will need to give it a different name.

**Comment by sumeetn** [comment]
thank you.
