### ISSUE TITLE
FetcherDeferredOpt does not extends DeferredOpt

### ISSUE THREAD

**Issue by bschaff** [sangria-graphql/sangria#188]
Hi,

Sorry to open an issue for that instead of doing a pull request but it seems that there is a typo concerning the FetcherDeferredOpt case class.

Maybe it's a misunderstanding or a bad usage on my part but it seems that the class FetcherDeferredOpt
should extends from DeferredOpt but right now it extends from DeferredOne which causes some compilation errors when you try to fetch from an optional value.

Could you confirm that ?

Thanks in advance.

Note: the full class with package is sangria.execution.deferred.FetcherDeferredOpt

**Comment by OlegIlyenko** [comment]
Thanks a lot for the report! The reason it does not fail any test is that fetcher internally pattern matches on `FetcherDeferredOpt` and `DeferredOpt`. But you are absolutely right, it should be `DeferredOpt`. I fixed it :)

**Comment by bschaff** [comment]
Thanks!
