### ISSUE TITLE
maxQueryDepth determinable before execution?

### ISSUE THREAD

**Issue by phuu** [sangria-graphql/sangria#191]
I'd like to be able to send an HTTP 400 Bad Request to clients whose query will exceed the maximum depth.

Is that determinable during query analysis or query reducing so I can fail-fast?

I might have this wrong though: is the whole point of the max depth error that you get a partial success response?

Thanks!

**Comment by OlegIlyenko** [comment]
You are right, `maxQueryDepth` on executor results in partially successful queries where deeper fields are not executed and result in error.

That said, I definitely agree with the use-case you have described. So I have implemented a query reducer that does precisely this. You can use it with `QueryReducer.rejectMaxDepth` or `QueryReducer.measureDepth` query reducers and this is completely static query analysis, so query would not be executed if query depth is reached provided threshold.

Before new version is released, I can recommend you to check out [`MeasureQueryDepth`](https://github.com/sangria-graphql/sangria/blob/e96523f28d6b3dd88c13c4065fe3ec249af327fa/src/main/scala/sangria/execution/QueryReducer.scala#L102-L132) if you would like to try it.

**Comment by phuu** [comment]
This is awesone work, thank you Oleg. I'll try it out as soon as I can.
