### ISSUE TITLE
Fetching Relation Typing

### ISSUE THREAD

**Issue by weiyinteo** [sangria-graphql/sangria#193]
I am trying to learn the Fetch API to fetch entities using the relation and found the example in the 
FetcherSpec.

```scala
val defaultProdFetcher = Fetcher.relCaching[Repo, Product, String](
      (repo, ids) ⇒ repo.loadProducts(ids),
      (repo, ids) ⇒ repo.loadProductsByCategory(ids(prodCat)))
```

Here both the Product and Category has String type. However, when Product has ProductId as its id and Category has CategoryId as its id, I suppose the String above should be changed to ProductId as follows

```scala
  val defaultProdFetcher = Fetcher.relCaching[Repo, Product, ProductId](
      (repo, ids) ⇒ repo.loadProducts(ids),
      (repo, ids) ⇒ repo.loadProductsByCategory(ids(prodCat)))
```

This works for `repo.loadProductIds` as it expects `Seq[ProductId]`, but no longer works for `repo.loadProductsByCategory(ids(prodCat))`. The `repo.loadProductsByCategory` expects `Seq[CategoryId]`, but it is called with `Seq[ProductId]`, given that `ids` is of type `Map[Relation[Prod, _], Seq[ProductId]]`.

**Comment by OlegIlyenko** [comment]
This is a very good point! the `fetchRel` function should be `Map[Relation[Prod, CategoryId], Seq[CategoryId]] ⇒ Future[Seq[Product]]`. I would consider it a bug (the type signature needs to be updated). I probably should have used different types for relation and entity ID in the tests

**Comment by weiyinteo** [comment]
Great. Looking forward to seeing the new type signature.
