### ISSUE TITLE
SimpleFetcherCache does not cache Relation.

### ISSUE THREAD

**Issue by weiyinteo** [sangria-graphql/sangria#194]
I was testing the Fetcher caching and found that the relations were not cached at all. Looking at the code for SimpleFetcherCache.
```scala
 def update(id: Any, value: Any) = {
    if (cacheable(id))
      cache.update(cacheKey(id), value)
  }

  def updateRel[T](rel: Any, relId: Any, idFn: (T) ⇒ Any, values: Seq[T]) = {
    if (cacheableRel(rel, relId)) {
      values.foreach { v ⇒
        update(idFn(v), v)
      }

      cache.update(cacheKeyRel(rel, relId), values)
    }
  }
```

I think there is a typo in `updateRel`, the `cache.update(cacheKeyRel(rel, relId), values)` should really be `relCache.update(cacheKeyRel(rel, relId), values)`.

**Comment by OlegIlyenko** [comment]
Thanks a lot for careful testing and reporting these issues! I fixed it and added a test for it (i completely forgot to add a relation cache tests).

For your convenience, I also published it in a snapshot (together with the other fix):

```scala
resolvers += "Sonatype snapshots" at "https://oss.sonatype.org/content/repositories/snapshots/"
libraryDependencies += "org.sangria-graphql" %% "sangria" % "1.0.0-RC6-SNAPSHOT"
```

**Comment by weiyinteo** [comment]
It is great to have such a quick turnaround, very much appreciated.
