### ISSUE TITLE
Comment parser should handle tailing comment

### ISSUE THREAD

**Issue by hepin1989** [sangria-graphql/sangria#219]
Seems like the current parser did not handle the tailing comments,
like 
```
{
#comment1
field1 #comment2
field2
}
```
here，`#comment2` should be a tailing comment of `field1`,not a comment of `field2`

![image](https://cloud.githubusercontent.com/assets/501740/23341226/3ab5e850-fc7e-11e6-9c5b-22d83a77c435.png)

**Comment by OlegIlyenko** [comment]
Good catch, thanks for reporting! `Field` does have `trailingComments`, but looks like rendering algorithm puts them in a wrong place :)

**Comment by hepin1989** [comment]
no,it doesn't:)

**Comment by OlegIlyenko** [comment]
oops, looks like I jumped into conclusions too quickly. `#comment2` looks in the right place, it's just assigned to a second field. 

I think it would be a tricky to parse it in a way that preserves this information about comment placement, but let's see what I can do.

**Comment by hepin1989** [comment]
I think how about add a new field `trailing:Boolean = false` to the `comment`.
and add a new type of parser eg `TrailingComment` to the definition,and then try to parse it after a token,this type of Comment will end up with `\n`or \r\n`.
