### ISSUE TITLE
Docs: deriveEnumType in companion object

### ISSUE THREAD

**Issue by tekacs** [sangria-graphql/sangria#221]
Since this took me way too long to figure out, I thought I'd share and ask for it to be added to the docs.

Ideally, we'd like to put the children of an 'enum' in its companion object (so they're namespaced and also so we can use [enumeratum][]).

As well as that (and this is the focus of this issue), we'd like to put the implicit enum type in the companion object, so that we don't have to perform a separate import to fetch it.

From the docs right now, it's not obvious how to do this.

This code compiles, under Scala 2.11:

```scala
import sangria.schema.EnumType
import sangria.macros.derive.deriveEnumType

sealed trait Shape
object Shape {
  case object Rectangle extends Shape
  case object Circle extends Shape

  implicit val enumType: EnumType[Shape] = deriveEnumType[Shape]
  //                     ^^ this is essential
}
```

The important thing to note is that the type annotation presumably forces evaluation of the expression in question to be after the type has been closed. Without the annotation, this doesn't compile.

[enumeratum]: https://github.com/lloydmeta/enumeratum

**Comment by OlegIlyenko** [comment]
Thanks a lot for documenting this behaviour! I added some labels, so hopefully, it would easier for others to discover it. I will also try to incorporate this info in the docs.
