### ISSUE TITLE
Update missing character in document 

### ISSUE THREAD

**Issue by GregYeo** [sangria-graphql/sangria#227]
I found missing character in document(http://sangria-graphql.org/learn/).

<img width="858" alt="screen shot 2017-03-10 at 8 25 04 pm" src="https://cloud.githubusercontent.com/assets/15027781/23793651/b3a4b444-05cf-11e7-8b09-1a08070bf3e9.png">

The Article class case should end with ')'. it is not closed completely.

**Comment by OlegIlyenko** [comment]
Ooops :) Thanks for a careful read! Would you like to submit a PR? This is the relevant file: 

https://github.com/sangria-graphql/sangria-website/edit/master/learn.md
