### ISSUE TITLE
add scalaz support

### ISSUE THREAD

**Issue by andykais** [sangria-graphql/sangria#229]
Both [doobie](https://github.com/tpolecat/doobie) and [http4s](https://github.com/http4s/http4s) use scalaz, and it would be awesome if there was support within sangria. I see monix is supported, which already has streams similar to scalaz so I feel like implementing this wouldnt be too extreme.

The obvious reason for this is the benefits that come with using one asynchronous method for all parts of an api. Currently, my method is getting a request, sending it through sangria, resolving it, then "awaiting" the Future and sending it off to http4s.

**Comment by OlegIlyenko** [comment]
It would be great if you can describe in more detail which kind of integration you would like to see.

Monix `Observable`s are indeed supported for subscription queries. There is also also one in works for FS2: 

https://github.com/dwhitney/sangria-fs2. 

Do you mean something like this?

> then "awaiting" the Future and sending it off to http4s

I'm pretty sure that you don't need to await on `Future`. I know several project that use sangria with http4s and, AFAIR, they just convert/adopt scala's `Future` to `Task` which you can then use with http4s.

The native support for `Task` as an alternative to scala's `Future` is not complex matter. It was discussed in detail in [the gitter channel](https://gitter.im/sangria-graphql/sangria), so I would suggest to search it for relevant discussions.

**Comment by andykais** [comment]
ah, fair enough. In http4s, it turns out you can do this
```scala
HttpService {
  case GET -> Root =>
  {
    Ok(Future("message from the future"))
    // yields: scalaz.concurrent.Task[org.http4s.Response]
  }
}
```

I my reasoning was the clarity that comes with using one asynchronous method for every part of an application, as well as no need for a global execution context, making my code more functional.

I will most likely use this until http4s `v0.16` arrives, which replaces scalaz & scalaz-stream with cats & fs2, (this is also supported by doobie).
