### ISSUE TITLE
Automatic object derivation for complex types

### ISSUE THREAD

**Issue by meddulla** [sangria-graphql/sangria#231]
Hi,

If I have a case class with complex types, e.g..

```
case class IndexComponentDb(id: String, name: String, weight: Double)
case class ShareClassMetaDb(
                             id: UUID,                             
                             countriesOfSale: Set[String],
                             status: String,
                             benchmarks: List[IndexComponentDb],
                             [...])
```
and then do automatic object derivation
```
val ShareClassType: ObjectType[ShareClassModel.type, ShareClassMetaDb] = {
    deriveObjectType[ShareClassModel.type, ShareClassMetaDb](
      ObjectTypeName("ShareClass"),
      ObjectTypeDescription("A share class."),
      ExcludeFields("id"))
  }
```

then these kinds of errors appear: 

```
Can't find suitable GraphQL output type for Set[String], 
Can't find suitable GraphQL output type for List[IndexComponent] 
```

Once we have GraphQL types for the base types, in this case, String and IndexComponent, can't Sangria automatically derive List's and Set's of them?

I can define a  GraphQL output type for Set[String] but it doesn't make much sense.. so I think I'm probably missing something. 

So how does one provide an output type in these kinds of cases?

Thanks!

**Comment by OlegIlyenko** [comment]
The `List` (in fact any `Seq`) is supported, but `Set` yet supported. I would suggest to use some Seq instead or use `ReplaceField` macro setting to transform a set into a sequence just for GraphQL type.

You will also need to define/import an implicit instance of `OutputType[IndexComponentDb]` somewhere in scope to get rid of the second compilation error.

**Comment by meddulla** [comment]
Thank you, `ReplaceField` was what I needed 👍  

Now another question :) How about maps? I know they don't  make much sense in this context but if we were to implement an `OutputType` for `Map[String, String]` it would have to be something akin to raw json right, similar to this https://gist.github.com/OlegIlyenko/5b96f4b54f656aac226d3c4bc33fd2a6 perhaps?

@OlegIlyenko Thank you so much for your help - sangria (and especially the macros) has been great!

**Comment by OlegIlyenko** [comment]
Thank you for your kind words! 🙇 

Using a raw JSON scalar can be an option, but I would discourage using it, especially considering that you have simple `String` values in the Map. I would suggest you to check out this issue: https://github.com/facebook/graphql/issues/101. I also commented there. I think there you can find several solutions on how to model it.

**Comment by meddulla** [comment]
Sorry for the long delay but been on holidays. That link provided some useful clues on how to solve this, so thanks :)

**Comment by kflorence** [comment]
Just ran into this. Might be nice to mention somewhere in the README a list of gotchas like this to save people some time.
