### ISSUE TITLE
Proveide more options to render a schema

### ISSUE THREAD

**Issue by OlegIlyenko** [sangria-graphql/sangria#241]
In particular it should be possible to opt-in following types:

* Built-in types (`Int`, `String`, etc)
* Sangria built-in (`BigDecimal`, `Int`, etc)
* Introspection types (`__Type`, `__Schema`, etc.)

It should be also possible to render schema directly to AST.

**Comment by OlegIlyenko** [comment]
The schema rendering got a lot of improvements! First, `SchemaRenderer` now produces an AST instead of rendering directly to a string.

`Schema` and `IntrospectionSchema` got following convenience methods:

* `toAst` - get GraphQL IDL AST for a schema instance 
* `renderPretty`
* `renderCompact`

All mentioned methods now also take additional argument: `SchemaFilter`. Some of the pre-defined filter:

* `withoutSangriaBuiltIn`
* `withoutGraphQLBuiltIn` 
* `withoutIntrospection`
* `builtIn`
* `introspection` 
* `all` 

For relay modern, you probably want to generate IDL with built-in sangria-specific types, but without any other built-in types like this:

```scala
schema.renderPretty(SchemaFilter.withoutGraphQLBuiltIn)
```

**Comment by dispalt** [comment]
This looks great to me, I haven't tried it but this seems like a great improvement.  Long and BigDecimal tripped me up and judging by the code, it looks like this fix would work well.

**Comment by dispalt** [comment]
Confirmed works well with 1.2.1
