### ISSUE TITLE
Deferred fetch for field groups

### ISSUE THREAD

**Issue by meddulla** [sangria-graphql/sangria#244]
Let's say that we have information of the same entity that is split into 2 separate tables, the core information and the meta information. The core info is used e.g. in listings and the meta information is used less frequently. Now, in the rest api all this info is the same json node:

```
{
id // core
name // core
description //meta
bio //meta
}
```
And we simply get the information from both tables and place them in the json node.

In the graphql, I have schema similar to this:

```
type User {
id: UUID
name: String
meta: UserMeta {
  description: String
  bio: String
  }
}
```
where there's a `User` resolver that goes to the core user table, and a `UserMeta` resolver that fetches the data when `meta` is included.

What I would prefer is a flattened schema like this:
```
type User {
id: UUID
name: String
description: String // meta
bio: String // meta
}
```

but without always getting data from both tables if possible. So only fetch data from the meta table if either description or bio are in the requested fields, but of course only do that query once for all the fields in the meta section. 

Is this at all possible? 

Thanks!

**Comment by OlegIlyenko** [comment]
Sure, I would suggest you to use `Fetcher` for this. I assume that you can get `UserMeta` using a user ID:

```scala
val userMetaFetcher = Fetcher.caching((ctx: MyCtx, ids: Seq[UUID]) ⇒ loadUserMetaForIds(ids))

// ... later on ....

ObjectType("User", fields[MyCtx, User](
  Field("id", UUIDType, resolve = _.value.id),
  Field("name", UUIDType, resolve = _.value.name),
  Field("description", StringType,
    resolve = c ⇒ DeferredValue(userMetaFetcher.defer(c.value.id)).map(_.description)),
  Field("bio", StringType,
    resolve = c ⇒ DeferredValue(userMetaFetcher.defer(c.value.id)).map(_.bio))
))
```

**Comment by meddulla** [comment]
Ohh.. I just reread the docs for Fetcher and saw that it handled deduplication and that, plus caching has everything I need! I thought that it would receive a list of 2 (equal ids) and so would call the resolver twice. Missed that deduplication bit somehow. Thanks a lot :)
