### ISSUE TITLE
Allow coercion errors to be handled by sangrias custom exception handler

### ISSUE THREAD

**Issue by BjRo** [sangria-graphql/sangria#252]
Extracted from #248 

This one came up during our current project. We noticed some inconsistencies in the errors we expose through our app. Just to give you an idea what our use case is: Our product basically extends sangrias errors before sending them to the client. This is mostly done for clients so that understanding `GraphQL` errors becomes less challenging for them. This includes for instance adding an error id to the error (such as `RESOLVE_FAILED`, or `QUERY_ANALYISIS_FAILED`). Or adding a `details` field, which further describes the error. All of our errors are handed out in the same format. 

This is roughly how we do it:
 
```scala
object Exceptions {
  import StatusCodes._

  val sangriaRuntimeExceptionHandler: Executor.ExceptionHandler = {
    case (m, ex: MissingParentFieldError) => {
      val details = Seq("fieldName" -> m.scalarNode(ex.fieldName, "String", Set.empty))

      HandledException("Missing field in parent selection",
                       Map(
                         "id"      -> m.scalarNode("MISSING_PARENT_FIELD", "String", Set.empty),
                         "details" -> m.mapNode(details)
                       ))
    }

    case (m, ex: RequestError) => {
      HandledException(
        "Could not resolve field",
        Map[String, ResultMarshaller#Node](
          "id"      -> m.scalarNode("RESOLVE_ERROR", "String", Set.empty),
          "details" -> (ex.json.getOrElse(JObject()): Json4sJacksonResultMarshaller.Node)
        )
      )
    }

    case (m, _: MissingIdError) => {
      HandledException(
        "This node needs to request the 'id' field because it's batched",
        Map(
          "id"      -> m.scalarNode("RESOLVE_ERROR", "String", Set.empty),
          "details" -> m.mapNode(Seq())
        )
      )
    }

    case (m, _) => {
      HandledException("Could not resolve field",
                       Map(
                         "id"      -> m.scalarNode("RESOLVE_ERROR", "String", Set.empty),
                         "details" -> m.mapNode(Seq())
                       ))
    }
  }

  def mask(throwable: Throwable): (StatusCode, JObject) = throwable match {
    case ex: SyntaxError =>
      val position = ex.originalError.position
      toError("SYNTAX_ERROR", "The supplied query contains syntax errors", ("line" -> position.line) ~ ("column" -> position.column))

    case ValidationError(violations, _) =>
      val details: JObject = "violations" -> violations.map(_.errorMessage)
      toError("QUERY_ANALYSIS_ERROR", "The supplied query contains semantic errors", details)

    case VariableCoercionError(violations, _) =>
      val details: JObject = "violations" -> violations.map(_.errorMessage)
      toError("ERRONEOUS_VARIABLES", "The supplied variables don't fulfill the schema requirements", details)

    case UnauthorizedAccessException =>
      toError("ACCESS_NOT_ALLOWED", "User credentials missing or invalid", statusCode = Unauthorized)

    case _ =>
      toError("INTERNAL_SERVER_ERROR", "Ooops, something unexpected happened while executing the request ...", JObject(), InternalServerError)
  }

  private def toError(name: String, description: String, details: JObject = JObject(), statusCode: StatusCode = BadRequest): (StatusCode, JObject) = {
    val jsonError = ("id" -> name) ~
      ("message"   -> description) ~
      ("locations" -> JArray(List())) ~
      ("path"      -> JArray(List())) ~
      ("details"   -> details)

    val json = ("data" -> JNull) ~ ("errors" -> List(jsonError))

    statusCode -> json
  }
}
```

The new coercion error introduced by #248 would be the only one that we can't really handle that way. So the question for this issue would be, can we make this work somehow?

**Comment by BjRo** [comment]
@OlegIlyenko Any plans for this? Or can we somehow help making this happen?

**Comment by OlegIlyenko** [comment]
Sorry, haven't looked it in detail yet. I will try to do it soon

**Comment by OlegIlyenko** [comment]
@BjRo now it should be possible to define custom error handling for any kind of error, including `Violation` and `UserFacingError` (which were handled exclusively by execution engine). I could not really make it a part of standard exception handling since it would be a major non-obvious breaking change in behavior (will not play nicely with catch-all handlers). Current implementation still introcuses a breaking change, but it is a minor one. 

*The migration stragegy*

before 

```scala
val exceptionHandler: Executor.ExceptionHandler = {
  case (m, ...) ⇒...
})
```

after

```scala
val exceptionHandler = ExceptionHandler {
  case (m, ...) ⇒...
}
```

*Example*

Here is an example: https://github.com/sangria-graphql/sangria/blob/9a5aed829d977badc769f17310357ac464039a63/src/test/scala/sangria/execution/ExceptionHandlingSpec.scala#L135-L140

**Comment by BjRo** [comment]
@OlegIlyenko This looks pretty cool. I'm back from tomorrow and will give it a spin. The breaking change is not really a problem for us. Thank you a lot!

**Comment by rogern** [comment]
I ran into this after upgrading sangria, would you be so kind to update the docs with this as well? @OlegIlyenko thanks!

**Comment by rogern** [comment]
@OlegIlyenko nm that the first example didnt work, my bad. But thrown Exceptions is still handled by onViolation and onError... is that how it is supposed to work?
