### ISSUE TITLE
Use type arguments in deriveObjectType

### ISSUE THREAD

**Issue by prismec** [sangria-graphql/sangria#261]
I try to return a value of

    case class MyValue[A](value: Option[A])

When I try to derive it from using a macro

    deriveObjectType[Unit, MyValue[Double]]()

it fails withe compile error: 

    Error:(25, 98) Can't find suitable GraphQL output type for Option[A]. If you have defined it already, please consider making it implicit and ensure that it's available in the scope.

**Comment by OlegIlyenko** [comment]
Thanks for pointing this out. This is not yet supported. I think it would be possible to implement it, but I'm not 100% sure yet. I will investigate it.
