### ISSUE TITLE
Slick date scalar types

### ISSUE THREAD

**Issue by jregistr** [sangria-graphql/sangria#283]
@OlegIlyenko I was thinking of adding new Scalar types backed by the date types that Slick supports out of the box, i.e: _java.sql.Date, java.sql.Time, java.sql.Timestamp_. What do you think
about this? 
It seems a little unrelated so I was thinking perhaps make it as an external module that others could add as a dependency should they need.

**Comment by OlegIlyenko** [comment]
I like the idea of providing standard date and time scalar types in a library. I think it would be better to have it in a separate library though. Date and time scalars have a lot of complexity associated with them, and in many cases, the actual implementation is use-case/project specific. Just looks at this huge discussion around this topic :) https://github.com/graphql/graphql-js/pull/557

So I would definitely encourage you to publish a library that provides date/time scalars (and maybe even some nice goodies for Slick integration?).

**Comment by jregistr** [comment]
Thank you, that was quite an interesting discussion. And I totally agree, the lib path is definitely the way to go with something like this.
