### ISSUE TITLE
Pagination not supported

### ISSUE THREAD

**Issue by ross-oreto** [sangria-graphql/sangria#284]
I can't seem to execute any query which includes pagination as specified in the graphql spec docs:

http://graphql.org/learn/pagination/#pagination-and-edges

For example this should return only 2 friends but instead results in a parsing error
```
{
  hero {
    name
    friends(first:2) {
      name
    }
  }
}
```
I'm tried this query on the sangria playground: [live demo](http://try.sangria-graphql.org/?query=%7B%0D%0A++hero+%7B%0D%0A++++name%0D%0A++++friends%28first%3A2%29+%7B%0D%0A++++++name%0D%0A++++%7D%0D%0A++%7D%0D%0A%7D)

**Comment by omerzach** [comment]
You need to add a `first` argument on the `friends` `Field` and implement the pagination logic yourself

**Comment by OlegIlyenko** [comment]
Yep, GraphQL does support field arguments but does not prescribe any particular semantics. What you are referring to is the Relay-based schema design & conventions. It defines things like `Connection` type and standard way to paginate. If you would like to use these conventions in your GraphQL server, I would recommend you to check out [sangria-relay](https://github.com/sangria-graphql/sangria-relay). There is also [live demo for it](http://try-relay.sangria-graphql.org/?query=%7B%0D%0A++rebels+%7B%0D%0A++++ships%28first%3A+2%29+%7B%0D%0A++++++edges+%7B%0D%0A++++++++node+%7B%0D%0A++++++++++name%0D%0A++++++++%7D%0D%0A++++++%7D%0D%0A++++%7D%0D%0A++%7D%0D%0A%7D%0D%0A)

**Comment by ross-oreto** [comment]
Thanks I'll check out sangria-relay. 
There also seems to be an issue with the sangria-relay demo at the moment everything even the default page query results in an error.

**Comment by OlegIlyenko** [comment]
Thanks for pointing this out, I also noticed it. I think it is a config issue. I'll check it
