### ISSUE TITLE
Nested InputObjectType with same property names

### ISSUE THREAD

**Issue by pgorin** [sangria-graphql/sangria#292]
Hi, I'm not sure if it is a bug or not, but when I define an input type (with nested objects) which have more than one input field with the same name (obviously in different nested objects) I have an error when executing a mutation.

DuplicateInputFieldViolation is thrown. I think that this validation should perform in the same object and not between nested ones. I am correct?

Error message: "...there can be only one input field named id..."

Example:

```graphql
mutation M {
  test: testMutation (
    user: {
      id: '1234',
      parent: {
        id: "5678"
        roles: []
      }
      roles: []
    }
  ) {
    result
  }
}
```

Thanks a lot!

**Comment by OlegIlyenko** [comment]
It's a sneaky one, thanks a lot for reporting this bug!

**Comment by pgorin** [comment]
Great, thanks to you!
