### ISSUE TITLE
Subscription - Executor not matching streamed events to prepared queries

### ISSUE THREAD

**Issue by jodagm** [sangria-graphql/sangria#295]
Trying to implement the subscription support. 
The server is connected to kafka stream of events and communicate to the clients over a websocket.

I followed the subscription-support-ws example.
The server now holds prepared queries, but when an event is sent to Executor for evaluation null is returned

looking into the Executor code, I see that I'm getting to the None case
```
	case ast.OperationType.Subscription ⇒
              tpe.uniqueFields.head.tags.collectFirst{case SubscriptionField(s) ⇒ s} match {
                case Some(stream) ⇒
                  // Streaming is supported - resolve as a real subscription
                  resolver.resolveFieldsSubs(tpe, root, fields)(scheme).asInstanceOf[scheme.Result[Ctx, marshaller.Node]]
                case None ⇒
                  // No streaming is supported - resolve as a normal "query" operation
                  resolver.resolveFieldsPar(tpe, root, fields)(scheme).asInstanceOf[scheme.Result[Ctx, marshaller.Node]]
              }
```
The difference between Streaming supported vs. not supported is not clear to me in the context of Oprtaion.Subscription
how can a subscription be resolved as normal query?

tpe.uniqueFields does contain the collection of event types from the schema definition
I am building the subscription schema following the same pattern in the example, using

```
case class SubscriptionField[+T: ClassTag](tpe: ObjectType[MyContext, T@uncheckedVariance])
```
Any guidance would be greatly appreciated
Jonathan

**Comment by OlegIlyenko** [comment]
Hmm, it looks like the subscription type is defined incorrectly. Can you please check that you used `Field.subs` in your `Subscription` type?. Here is an example: https://github.com/sangria-graphql/sangria-subscriptions-example/blob/master/src/main/scala/schema.scala#L70

In general, if you are using stream-based subscriptions, you don't need to prepare the query (with `Executor.prepare`), Maybe you can make a small self-contained example that reproduces the issue? (just to see all of the parts: query, execution and the schema shape) It would help a lot.

**Comment by jodagm** [comment]
Thank you Oleg,
indeed, I was not using Field.subs (used the web socket example for reference as I am trying to stream the subscription events through websocket)
I will follow the example you sent.
