### ISSUE TITLE
Deferred resolution during HandledException

### ISSUE THREAD

**Issue by apatzer** [sangria-graphql/sangria#299]
One of the things I love about Sangria is being able to use lazy Fetchers. That makes it convenient, for example, to resolve a `userId` on a case class into a full User object when needed:

```
resolve = { c: Context[_, User] =>
  c.value.map(_.fullName)
}
```

I would love to be able to do this during a HandledException as well, by providing a `Context[Ctx, Val] ⇒ Action[Ctx, Res]`

```
Executor.ExceptionHandler = {
  case (_, PetOwnerException(msg, numPets, ownerUserIdOpt)) => HandledException(resolve = { context =>
    DeferredValue(userFetcher.deferOpt(c.value.ownerUserIdOpt)).map {
      case Some(user) => s"Owner ${user.fullName} cannot handle any more than $numPets"
      case None => msg
  })
}
```

Is there anyway to use a DeferredValue during exception processing? Or to accomplish something similar? By best solution now is something dirty like `await`.

**Comment by OlegIlyenko** [comment]
Unfortunately, it is not possible at the moment. `ExceptionHandler` is primarily meant for simple error/message transformations (which does not involve communication to external systems or async behaviour). This might be an interesting feature to consider though.

One possible solution to this would be to make the exception itself (`PetOwnerException`) self-contained. This would beam that it will already contain all necessary information to create a nice error message.

**Comment by apatzer** [comment]
That's probably best. Closing this for now.
