### ISSUE TITLE
Sangria client??

### ISSUE THREAD

**Issue by lonyele** [sangria-graphql/sangria#320]
Hi, I'm just curious if there is a client version of sangria?   I have set graphql server with sangria, but It seems like I can't communicate with other sangria server.     At node.js, I made multiple graphql servers with apollo-server library and communicate with each other(server to server) using the basic apollo-client library.  It seems like there is no client version at Scala. I found Apollo-android and trying it, but since I'm learning scala and sangria I wonder if I can stick to these technologies.

**Comment by OlegIlyenko** [comment]
Since sangria is a spec-compliant GraphQL implementation, all libraries (like apollo) should work with the sangria-based server. When it comes to scala-based clients, I would recommend you to check the community section of the documentation:

http://sangria-graphql.org/community/#projects

There are several projects that provide client functionality.

**Comment by lonyele** [comment]
Thanks for your reply. I already checked community section and google search in general, but I couldn't find a client implementation in scala... maybe I missed it. I tried apollo-android, but it was difficult for me... anyway, thanks for your help

**Comment by OlegIlyenko** [comment]
Yeah, at the moment scala-based GraphQL client ecosystem is still young. There are already some great projects that focus on a specific aspect of client infrastructure, like code generation, but I'm not aware of any full-featured scala-based GraphQL client library. A great opportunity for an exciting new scala project ;)

**Comment by lonyele** [comment]
Thanks a lot! I wish I have a skill to make a library...

**Comment by Jarlakxen** [comment]
I just started working on a small client https://github.com/jarlakxen/drunk/. Right now is just a small wrapper but I want to implement a lot of things.
