### ISSUE TITLE
Deferred resolution caching issue in subscriptions

### ISSUE THREAD

**Issue by apatzer** [sangria-graphql/sangria#321]
I have a subscription that uses a deferred resolver:
```
subscription {
  recordUpdate { lastModifiedBy {name}}
}
```
where
```
Field("lastModifiedBy", OptionType(UserType), resolve = c => UserResolver.deferOpt(c.value.modifiedById)) // What's stored is a UUID
...
UserResolver: Fetcher[MyContext, User, User, UUID] = Fetcher.caching(...)
```

On the first event-stream event, the UUID is resolved into a `User` object. However on subsequent events, the UUID is not resolved. A bit of breakpoint debugging shows that the cache seems to be regenerated every event (as opposed to per stream), but never even queried for the UUID, let alone making it to my resolver.

I'm using `play.api.libs.EventSource` which uses Akka streaming in case that's relevant.

**Comment by apatzer** [comment]
The issue is resolved if I use a `Fetcher` rather than a `Fetcher.caching`. Since Sangria caching fetches cache on a per query basis, what is the expected behavior for a long-running subscription?

**Comment by OlegIlyenko** [comment]
The default cache implementation is quite [simple](https://github.com/sangria-graphql/sangria/blob/master/src/main/scala/sangria/execution/deferred/FetcherCache.scala#L28) and it caches all values for the lifetime of the query execution. At the moment there is no special behaviour for the subscription queries. 

You can provide more sophisticated (LRU or TTL-based cache) cache implementation by implementing `FetcherCache` trait and providing it via `FetcherConfig`
