### ISSUE TITLE
Support @argumentDefinitions and @arguments

### ISSUE THREAD

**Issue by macalinao** [sangria-graphql/sangria#328]
https://medium.com/entria/relay-modern-argumentdefinitions-d53769dbb95d

These are needed for refetch containers to work properly.

**Comment by macalinao** [comment]
sorry i misread this

**Comment by OlegIlyenko** [comment]
As far as I understood, these directives are purely client side and are handled by the relay compiler. So they don't even reach the GraphQL server. Please correct me if I'm wrong.

**Comment by macalinao** [comment]
They are. I was mistaken
