### ISSUE TITLE
Fetcher.caching on unique keys for the same item

### ISSUE THREAD

**Issue by sachee** [sangria-graphql/sangria#338]
Any ideas on how to make the caching (i.e. `Fetcher.caching`) work when we have two unique keys for an item that aren’t both known up front?

For example, having something like `userId` and `username` that are interchangeable (and use the same query), it would be cool to be able to cache something queried by `username` and retrieve it from cache by `userId`.

This seems like a fairly common use case (looking up something by name first, and then by id).

**Comment by OlegIlyenko** [comment]
If you are using Fetch API, I think you define ID as a polymorphic type (it then can be either ID or username, as long as the username is unique). Though you would also need to customize the cache implementation a bit to handle both variations of identifiers.

You also might find this discussion interesting: https://github.com/sangria-graphql/sangria/issues/280

**Comment by sachee** [comment]
Thanks so much! I did something similar to what you linked in #280, and that works! 👍
