### ISSUE TITLE
gitter channel ?

### ISSUE THREAD

**Issue by chandu0101** [sangria-graphql/sangria#34]
Hi,
       How about having a gitter channel for this repo .. 

Steps : 
 login to  u r gitter account 
-> create Room
-> choose Repository
-> done (gitter will send a automated PR )

![screen shot 2015-06-25 at 8 12 12 am](https://cloud.githubusercontent.com/assets/2179670/8345854/626ae520-1b12-11e5-839d-ff13e1f24221.png)

**Comment by OlegIlyenko** [comment]
Sure, why not. I created a chat room and the badge :)
