### ISSUE TITLE
Using cats-effect IO instead of Future?

### ISSUE THREAD

**Issue by Malax** [sangria-graphql/sangria#349]
Is there a way to use `IO` instead of `Future` as the result of `Executor.execute`? That would mean that all my actions have to be pure and returning `IO` as well. I would really like to see sangria getting (optional) support for this.

I guess `Future` is the lowest common denominator for effectful actions that is available without introducing a new depedency, but If we could optionally allow to replace that effect with another (in this case `IO`) users are way more flexible.

I do not have a deep grasp about sangrias architecture, would that theoretically be possible to implement? What would we have to do? If this is something you would consider implemeting, I'd be happy to help!

**Comment by OlegIlyenko** [comment]
This question comes up every now and then. I definitely can see the appeal for generic handling of the effect type, like `Task`, `IO`, (twitter) `Future`, etc. (and I definitely see the appeal of the mentioned effect types themselves)

I think you got the motivation behind the scala `Future` choice right. My another concern is the added complexity of code (and possibly build), if effect type is parametrized (in a similar fashion as in fs2). At the moment the library already parametrizes on many things, like data format, user context, amount other things. Adding one more generic parameter into the mix would introduce quite a bit of complexity (internally for the library, but also, even more importly, for the users of the mobrary). So I don't want to take this decision lightly.

That said, I'm staying open for local/global improvements in this area. but at the moment there is no concrete plans to parametrize on the effect type or doing something more specific, like replacing the `Future` with `IO`.

**Comment by Malax** [comment]
Thanks for your elaborate response! I understand the reasoning of not mindlessly putting it in without putting proper thought into it. :) I'll just do some bridge code here and there to convert back and forth between `Future` and `IO`.
