### ISSUE TITLE
ResolverBasedAstSchemaBuilder does not know the Mutation type

### ISSUE THREAD

**Issue by magnusart** [sangria-graphql/sangria#354]
Hi

I posted about this issue in the gitter channel but got no responses, after debugging it a couple of times I can only conclude that this is a bug or at the very least an undocumented limitation.

When I use a resolver based builder that takes a SDL schema containing the Mutation type I get an exception on validation.

Example that produces the issue:
https://scastie.scala-lang.org/yDa6dOvxQeOKpaM7dNYYEA

Example that does not produce the same issue (mutation removed):
https://scastie.scala-lang.org/If8sunzfSBuVWLzI3pz6qg

I'm _suspecting_ the offending line is the following, only stubQueryType is included:
https://github.com/sangria-graphql/sangria/blob/97f2fa497551b558681efc8078096bd0183c37dc/src/main/scala/sangria/schema/ResolverBasedAstSchemaBuilder.scala#L41

The `KnownTypeNames` rule validates against this schema, which does not contain a Mutation type.

**Comment by OlegIlyenko** [comment]
Thanks a lot for reporting this. It was a bug in the validation - the standard validation rule (`KnownTypeNames`) should not validate these type names (validation is done in the materializer)
