### ISSUE TITLE
How to deal with nested deferred value

### ISSUE THREAD

**Issue by ChouUn** [sangria-graphql/sangria#356]
## Basic
I have 3 tables: User, Role, UserRole.  
The first two are entities, and the latter is relationship.  

## Current
If I want to get the roles which a user has, I have to get "userRoles" first that is so much trouble and not elegant enough. 

The implementation is as follows:
[Definition.scala#L24](https://github.com/ChouUn/doj-server/blob/d6cf2dda71bb3fdf75384c31f686d12c0507ab67/app/GraphQL/Definition.scala#L24)

## Trouble
I use another implementation
```scala
Field("roles", ListType(RoleType),
  resolve = ctx => {
    val deferUserRoles = userRolesFetcher.deferRelSeq(userRoleByUserRel, ctx.value.id)
    val deferRoleIds = DeferredValue(deferUserRoles).map(_.map(_.roleId))
    val deferRoles =
      deferRoleIds.map((roleIds: Seq[Int]) => {
        val tmp = rolesFetcher.deferSeq(roleIds)
        DeferredValue(tmp)
      })
    deferRoles
  }
)
```
but receive
```
[info] Compiling 5 Scala sources to /doj-server-scala/target/scala-2.12/classes ...
[error] /doj-server-scala/app/GraphQL/Definition.scala:28:12: sangria.schema.DeferredValue[Nothing,Seq[models.Role]] is invalid type for the resulting GraphQL type Seq[models.Role].
[error]       Field("roles", ListType(RoleType),
[error]            ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```
Other maybe solutions (like UpdateCtx) are similar.

Is there a correct way to solve it?
I have tried my best to read [documentation](http://sangria-graphql.org/learn/#deferred-value-resolution), [source codes](https://github.com/sangria-graphql/sangria/blob/master/src/main/scala/sangria/schema/Context.scala), demos, etc.

**Comment by OlegIlyenko** [comment]
Since it is many-to-many relation, I think you can define your relations like this:

```scala
val usersByRoleRel =
  Relation[User, (Seq[UserRole], User), Int]("usersByRole", 
    tmp ⇒ tmp._1.map(_.roleId)
    tmp ⇒ tmp._2)

val rolesByUserRel =
  Relation[Role, (Seq[UserRole], Role), Int]("rolesByUser", 
    tmp ⇒ tmp._1.map(_.userId)
    tmp ⇒ tmp._2)
```

`UserRole` is just an intermediate data structure. In this variation, you also working with intermediate value `(Seq[UserRole], T)`, which you would also need to return in the fetchers.

There is one example project available that demonstrates this approach in more detail (as well as many-to-many relations in general):

https://github.com/steveluscher/zero-to-graphql/blob/master/zero-scala/src/main/scala/SchemaDefinition.scala#L9-L14

**Comment by ChouUn** [comment]
It works very well, and the implementation is very elegant.
I'm sorry that although I have seen this demo, I did not realize this usage at the time, because the relationship of people is between themselves, that makes me ignore it.

**Comment by helkaroui** [comment]
@ChouUn I'm working on the same use case, I have a many-to-many relation witch an intermediate table. 
Could you please share with us a simple example on how you did it ?
Thanx

**Comment by ChouUn** [comment]
@helkaroui sorry for no response because of busy work
The solution is the same as [above](https://github.com/sangria-graphql/sangria/issues/356#issuecomment-381633472)
My code: https://github.com/ChouUn/doj-server/blob/master/app/doj/sangria/Definition.scala#L42
