### ISSUE TITLE
Read Authorization Header or cookie

### ISSUE THREAD

**Issue by samudurand** [sangria-graphql/sangria#364]
I use Auth0 to perform my authentication on the client side, because it's easy and avoid having to maintain a DB with the users details on the server side. It also avoid having to perfomr a graphql mutation for the Login feature.

But I still need to secure my endpoints and for that I need to send the token generated by Auth0 from my UI to my backend with every request, in order to verify if the user is authenticated. 

On a classic Rest API no problem, I would either add the token to every request either in the Authorization header or a token cookie. But I couldn't find any instruction on how to extract the headers or cookies with Sangria. Any help ?

**Comment by OlegIlyenko** [comment]
You need to handle the headers or cookies on the HTTP layer. Sangria itself does not know anything about the transport protocol (e.g. HTTP):

![app layers](https://sangria-graphql.org/assets/img/stack.svg)

In practice this means that you just need to analyzed the incomming HTTP request and its headers and then approprietly execute the query. You can store the the auth information in the context object. By doing this you are making it available to all GraphQL field resolvers and middleware. 

For more information on possible authorisation implementation, I would recommed to check out ["Authentication and Authorisation"](https://sangria-graphql.org/learn/#authentication-and-authorisation) section of the documentation.

**Comment by samudurand** [comment]
Thanks for the answer, that clarifies some things. But I have no idea where to start to perform something in the previous layer, before Sangria start handling it. I am guessing I need to read the header there and convert it in some way that Sangria can understand, maybe modify the body by adding a token in the JSON sangria receives ? The section you referred only explains how to login and perform an action at the same time. Not how to retrieve an existing authentication token I think.

**Comment by samudurand** [comment]
Ok my bad, I had completely forgot that my app is just a normal akka-http server with the usual routes, the graphql part is as you explained just an intermediary level between those routes and the business logic.
