### ISSUE TITLE
Using ScarType with an InputObjectType

### ISSUE THREAD

**Issue by pulasthibandara** [sangria-graphql/sangria#369]
Hi @OlegIlyenko, I have another question in relation to #368  (MiddlewareFromScalar), and I really appreciate all the guidance on the previous issue.

Assume that I have defined a ScalarType like
```scala
  case class Test(part1: String, part2: String)

  implicit val TestType: ScalarType[Test] = ScalarType[Test]("TestScalar",
    coerceUserInput = {
      case s: String => s.split(".").toList match {
        case a :: b => Right(Test(a, b.mkString("")))
        case a :: Nil => Right(Test(a, ""))
        case Nil => Right(Test("", ""))
      }
      case _ => Left(DateTimeCoerceViolation)
    },
    coerceOutput = (dt, _) => ast.StringValue(dt.toString),
    coerceInput = {
      case ast.StringValue(s, _, _, _, _) => s.split(".").toList match {
        case a :: b => Right(Test(a, b.mkString("")))
        case a :: Nil => Right(Test(a, ""))
        case Nil => Right(Test("", ""))
      }
      case _ => Left(DateTimeCoerceViolation)
    }
  )
```

Which basically divides the input string in to two and create the `Test` case object.

It works perfectly when I use the scalar type with an argument like `Argument("test", TestType)`.
However, when i try to use it in a InputObjectType like 

```scala
case class TestInput(id: String, test: Test)

object TestInpout {
    implicit val testInputReads: Reads[TestInput] = Json.reads[TestInput] // Im using play-json
    implicit val testInputType: InputObjectType[TestInput] = deriveInputObjectType[TestInput]()
}
```

I get a type error for not having an implicit object for `Reads[Test]`. Is there a good way to work around this and it it necessary define marshalling for  ScalarTypes?

**Comment by OlegIlyenko** [comment]
Does this error comes from the play-json? Have you tried to define an implicit `Reads[Test]`?

**Comment by OlegIlyenko** [comment]
I see. In general, during the de-serialization process value would travel through the middleware, you would get an opportunity to adjust it if necessary. But in case of the input objects, the de-serialization into a case class is delegated to a play-json (at least in this particular case). This means that in addition to a scalar type, you also need to define `Reads[Test]`. In this scenario, GraphQL input type provides information about the object structure and documentation and play-json is responsible for object runtime de-serialization.

That said, sangria provides a lot of flexibility in this respect. The deserialization is not coupled with play-json or any other JSON library. It relies on the `FromInput` type class. If you would like to implement an alternative deserialization mechanism, I would suggest you to check out these docs:

https://sangria-graphql.org/learn/#frominput-type-class

**Comment by pulasthibandara** [comment]
I tried defining a implicit Reads like this so it satisfies the implicit variable 
```implicit val testReads: Reads[Test] = (json: JsValue) => JsSuccess(Test("", ""))``` 

However, instead of the value resolved from the middleware, it passes the value from `Reads` in to the resolver.

I breakpointed the code within ScalarType and it does get called with the correct values. It just that the values that gets passed down to the resolver is the one generated from the implicit Reads object.

**Comment by OlegIlyenko** [comment]
Yeah, that's right. Tha data flow looks something like this:

input data (either variable JSON or GraphQL input value) → 
→ scalar type coercion  (`coerceUserInput` or `coerceInput`) → 
→ MiddlewareFromScalar.fromScalar →
→ (at this point the execution engine sees that input type has it's own `FromInput`-based de-serializer) →
→ `ScalarType.coerceOutput` → `MiddlewareToScalar.toScalar` →
→ (value is now serialized, but this time with the help of `FromInput.marshaller`) →
→ `FromInput.fromResult`

As you can see, the value is (1) deserialized with the custom scalar and middleware but then, after all sanity checks and validation is done, (2) it is serialized back to the play-json format in order use the play-jon's `Reads`.

Also note, that `RawResultMarshaller` (`CoercedScalaResultMarshaller` is an implementation or it) allows to skip the step (2) and directy work with values that were decerialized with `coerceUserInput` or `coerceInput`. Maybe this is what you can take advantage of?

**Comment by OlegIlyenko** [comment]
Also on a side note, the design of this mechanism allows for more efficient implementation of case class de-serialization of input objects which does not require the step (2). And it is something that you can implement with the help of `FromInput` type class (it's all type-class based). But so far, we only implemented `FromInput` instances for already existing and well-established scala case class marshalling libraries. This allows us to harvest all existing type classes like play's `Reads` or circe's semi-automatic derivation and fully automatic derivation.

**Comment by pulasthibandara** [comment]
Thank you @OlegIlyenko. You are Awesome! I took your clues and basically ended up doing something like this.

```scala
case class Test(part1: String, part2: String) 

object Test {
  implicit val testReads: Reads[Test] = Json.reads[Test]

  implicit val TestType: ScalarType[Test] = ScalarType[Test]("TestScalar",
      coerceUserInput = {
        case s: String => s.split(".").toList match {
          case a :: b => Right(Test(a, b.mkString("")))
          case a :: Nil => Right(Test(a, ""))
          case Nil => Right(Test("", ""))
        }
        case _ => Left(DateTimeCoerceViolation)
      },

      // ** return ast.ObjectValue that has the shape of Test **
      coerceOutput = (dt, _) => ast.ObjectValue(
          "part1" => ast.StringValue(dt.part1),
          "part2" => ast.StringValue(dt.part2),
      ),
      coerceInput = {
        case ast.StringValue(s, _, _, _, _) => s.split(".").toList match {
          case a :: b => Right(Test(a, b.mkString("")))
          case a :: Nil => Right(Test(a, ""))
          case Nil => Right(Test("", ""))
        }
        case _ => Left(TestCoerceViolation)
      }
    )
}
```

Returning a `ast.ObjectValue` instead of a `ast.StringValue` from `coerceOutput` enabled this to be marshalled to a JsObject, rather than a JsString. Which fixed the issue of transforming it back to the `Test` type.
