### ISSUE TITLE
How to run multiple mutations in a single transaction?

### ISSUE THREAD

**Issue by Ibrahim-Islam** [sangria-graphql/sangria#373]
I have multiple mutations that correspond to individual procs. I want to execute these mutations in a single transaction. How to facilitate that in Sangria?

```
mutation save {
    updateOne(id: 1) {
        name
    }
    updateTwo() {
        id
        name
    }
}
```

**Comment by OlegIlyenko** [comment]
If you would like to run all mutations in a single DB transaction, then I guess the simplest solution would be to to wrap the whole GraphQL query execution in a transaction.

**Comment by Ibrahim-Islam** [comment]
@OlegIlyenko Thank you for reply. Following is how I expose my mutation :

```
val mutationFields: List[Field[GraphQLContext, Unit]] =
fields[GraphQLContext, Unit](
    Field(
    name = "CreateMutation",
    fieldType = OptionType(customer),
    arguments = List(customerName),
    resolve = c => c.ctx.createCustomer(c.arg(customerName)),

   // other mutations exposed as fields
```
Since the consumer can batch up any combination of mutations together how do I resolve a request to run each mutation one after another? For example each service invocation is wrapped in a transaction e.g. `createCustomer`. Any example or code sample would be appreciated.

**Comment by OlegIlyenko** [comment]
All top-level mutation fields specified in a mutation query are always executed in a sequence (not in parallel, in contrast to normal query fields which might execute in parallel). This behaviour is a part of the GraphQL spec.

If we are talking about the SQL DB transactions, then you can define a transactions for every mutation field. In this case every mutation field (and it's transaction) would be independent.

If you want all mutation fields to be part of a transaction (so either all of them are successful or none of the mutation field's Db chnages` are applied), then you can wrap the whole query execution in a single transaction. Something along these lines:

```scala
wrapInTransaction { transactionContext ⇒
 Executor.execute(schema, query, userContext = transactionContext)
}
```

There are also alternative approaches to treat transactions. For example, you can only allow transactions within an aggregate root. Recently I wrote a blog post that describes this approach a bit:

https://techblog.commercetools.com/modeling-graphql-mutations-52d4369f73b1#fa6e
