### ISSUE TITLE
Extract Json AST support in separate libraries

### ISSUE THREAD

**Issue by OlegIlyenko** [sangria-graphql/sangria#38]
This probably will require additional project, something like `sangria-marshaling-api`. It then would be used by json integration libraries and sangria itself.

**Comment by guymers** [comment]
Do you mean having a core module with modules for each marshalling implementation that depend on the core module? Something like:

    sangria-marshalling-circe
    +-sangria
    +-circe libs

    sangria-marshalling-json4s
    +-sangria
    +-json4s libs

    sangria-marshalling-play
    +-sangria
    +-play libs

    sangria-marshalling-spray
    +-sangria
    +-spray libs

With the folder structure looking something like:

    core/
    marshalling/
                circe/
                json4s/
                play/
                spray/

**Comment by OlegIlyenko** [comment]
Almost. I was thinking about something like this:

    sangria
    +-sangria-marshaling-api

    sangria-marshalling-circe
    +-sangria-marshaling-api
    +-circe libs

    sangria-marshalling-json4s
    +-sangria-marshaling-api
    +-json4s libs

    sangria-marshalling-play
    +-sangria-marshaling-api
    +-play libs

    sangria-marshalling-spray
    +-sangria-marshaling-api
    +-spray libs

`sangria-marshaling-api` will then define a set of traits and maybe some default implementation. 

This will allow to decouple sangria versioning from Json support versioning. 

I really would like to make all mentioned libraries a separate git repos, not a fan of big and complex multi-module SBT builds. So the directory structure will not change that much.

**Comment by OlegIlyenko** [comment]
I also would like to do this a bit later, since these marshaling trais changing very often at the moment. But as soon as they become more or less stable, i think it would the right time to extract all json support in separate libraries and git repos.
