### ISSUE TITLE
Support ast schema generation from file

### ISSUE THREAD

**Issue by markarasev** [sangria-graphql/sangria#380]
One can generate an ast schema this way :
```scala
val ast = gql"""
  type Article {
    id: String!
    title: String!
    text: String!
    author: String
  }
  type Query {
    article(id: String!): Article
  }
"""
```
But the macro does not support string interpolation so I cannot do something like :
```scala
val schemaUrl = Thread.currentThread.getContextClassLoader.getResource("articles.graphql")
val source = Source.fromURL(schemaUrl)
val stringSchema = source.mkString
val ast = gql"""$stringSchema"""
```
With `articles.graphql` being a resource file containing :
```graphql
type Article {
  id: String!
  title: String!
  text: String!
  author: String
}
type Query {
  article(id: String!): Article
}
```
If I did not missed something there's nothing like :
```scala
val ast = AstSchema.fromResource("starwars.graphql")
```
It would enable working with `.graphql` files that are understood by all graphql developpers.
What do you think?

**Comment by OlegIlyenko** [comment]
Sangria provides good support for SDL-based schema definition. I would suggest you to check this part of the docs (as well as "High-level SDL-based Schema Builder" and "Schema Materialization Example" sections):

https://sangria-graphql.org/learn/#based-on-sdl-definitions

You should use `QueryParser.parse` instead of of `graphql` macro since the string is dynamic.

**Comment by markarasev** [comment]
Indeed, I missed that in the docs, thank you for your answer. Is there any reason to have this object name prefixed by `Query` if it is able to parse more than just a graphql query?

**Comment by OlegIlyenko** [comment]
Yeah, it's a good point. At the time when parser was introduced, the SDL part of the GraphQL syntax didn't existed yet. So the `QueryParser` name was quite fitting. meanwhile it also able to parse SDL as well as input values. This might be a good idea to rename it in future to just `Parser` or `GraphQLParser` or something similar (query and SDL syntax are part of the same grammar definition, so the parser should be able to handle both at the same time). Thanks for the hint, I got used to it so much that I haven't noticed this.
