### ISSUE TITLE
misleading pattern in the "learn" documentation

### ISSUE THREAD

**Issue by andyczerwonka** [sangria-graphql/sangria#384]
The [very first example on the website](https://sangria-graphql.org/learn/) suggests, what is in my opinion, is a bad pattern and would not want someone to assume that is the suggested pattern.

``` scala
// Parse GraphQl query
val Success(document: Document) = QueryParser.parse(query)
```

The example should be changed to either map over or pattern match the parsing result, handling the error case.

**Comment by OlegIlyenko** [comment]
Good point :+1: What do you think about this change? https://github.com/sangria-graphql/sangria-website/commit/3456cc264c995701f472aaa94e655ca3a2c84fe4
