### ISSUE TITLE
DeriveObjectType with Implicit Conversions?

### ISSUE THREAD

**Issue by kevinmu** [sangria-graphql/sangria#393]
Hello,

I'm working through an issue I'd love some advice on! The issue is described as succinctly as possible below:

I have defined a Joda `DateTime` custom scalar type following your example in the Sangria user guide: 
```
case object DateCoercionViolation extends ValueCoercionViolation("Date value expected")

def parseDate(s: String) = Try(new DateTime(s, DateTimeZone.UTC)) match {
  case Success(date) ⇒ Right(date)
  case Failure(_) ⇒ Left(DateCoercionViolation)
}

val DateTimeType = ScalarType[DateTime]("DateTime",
  coerceOutput = (d, caps) ⇒
    if (caps.contains(DateSupport)) d.toDate
    else ISODateTimeFormat.dateTime().print(d),
  coerceUserInput = {
    case s: String ⇒ parseDate(s)
    case _ ⇒ Left(DateCoercionViolation)
  },
  coerceInput = {
    case ast.StringValue(s, _, _) ⇒ parseDate(s)
    case _ ⇒ Left(DateCoercionViolation)
  })
```

Further, I have a case class which has the well-known Timestamp protobuf type as one of its fields.
```
case class File(
  name: String,
  lastModified: com.google.protobuf.timestamp.Timestamp
)
```
I'm trying to create a GraphQL type from this case class (where the `lastModified` field would have type `ScalarType[DateTime]`) with
```
implicit val File: ObjectType[UserContext, File] = deriveObjectType[UserContext, File]()
```
To support the macro, I've defined the following implicit conversion and imported it in the scope of the derive statement above:
```
import scala.language.implicitConversions
import com.google.protobuf.timestamp.Timestamp
import com.google.protobuf.util.Timestamps
import org.joda.time.DateTime
  implicit def toDateTime(timestamp: Timestamp): DateTime = {
    val millis = Timestamps.toMillis(Timestamp.toJavaProto(timestamp))
    new DateTime(millis, DateTimeZone.UTC)
  }
```

However, when I try to compile the above code I stil get  
``` 
[error]    Can't find suitable GraphQL output type for com.google.protobuf.timestamp.Timestamp. If you have defined it already, please consider making it implicit and ensure that it's available in the scope.
[error]     deriveObjectType[UserContext, File]()
```

Essentially, the behavior I was hoping for is that the `Timestamp` value gets implicitly converted to a `DateTime` value, which is then able to be converted to `ScalarType[DateTime]`. I was wondering if there is a different way to achieve this goal? Really appreciate any advice you might have; thanks!

**Comment by OlegIlyenko** [comment]
I think [scalar aliases](https://sangria-graphql.org/learn/#scalar-type-alias) might help in your scenario. For example:

```scala
implicit val TimestampType = ScalarAlias[Timestamp, DateTime](DateTimeType,
  toScalar = timstamp ⇒ /* logic to convert Timestamp → DateTime */,
  fromScalar = dateTime ⇒ /* logic to convert DateTime → Timestamp */)
```

**Comment by kevinmu** [comment]
This worked perfectly; thank you!
