### ISSUE TITLE
Any plan to support Automatic Persisted Queries (APQ)?

### ISSUE THREAD

**Issue by srenault** [sangria-graphql/sangria#394]

**Comment by OlegIlyenko** [comment]
I assume you are referring to [Apollo Engine feature](https://www.apollographql.com/docs/engine/proxy/guides.html#automatic-persisted-queries)? The features like persisted queries are one layer above the GraphQL layer. The goal of the library is to provide all necessary tools to build GraphQL servers and tools with Scala. So the library provides all necessary building blocks to implement features like APQ on top of it, but these probably would be different libraries (I'm not aware of a scala library that implements Apollo's APQ).

Also, I don't remember seeing a formal specification for Apollo's APQ protocol. Without a formal protocol it would be hard to provide an consistent alternative implementation.

**Comment by srenault** [comment]
Ok make sense. Thanks.
