### ISSUE TITLE
Allow specifying a marshallable value in custom ExceptionHandler

### ISSUE THREAD

**Issue by macalinao** [sangria-graphql/sangria#395]
https://sangria-graphql.org/learn/#custom-exceptionhandler

I'd like to be able to pass in a Circe `Json` instead of a `Map[String, ResultMarshaller.Node]`.

**Comment by OlegIlyenko** [comment]
You can convert circe JSON to `ResultMarshaller.Node` with `m.fromInput(cieceJson)` (`m` in this case is a `ResultMarshaller` which is provided as an argument). Would this help in your case?

**Comment by macalinao** [comment]
I am getting `value fromInput is not a member of sangria.marshalling.ResultMarshaller`

**Comment by OlegIlyenko** [comment]
which version sangria are you using? This function was added quite recently. (v1.4.1 I think)

**Comment by macalinao** [comment]
I am getting `value fromInput is not a member of sangria.marshalling.ResultMarshaller`

**Comment by macalinao** [comment]
I am on sangria 1.4.1, sangria-circe 1.2.1

**Comment by macalinao** [comment]
The function was found :smile: 

Is there an easy way for me to convert to a `Map`, because now I am getting this error:

```scala
[error]  found   : _1.m.Node where val _1: sangria.marshalling.MarshallingUtil.ResultMarshallerOps
[error]  required: Map[String,sangria.marshalling.ResultMarshaller#Node]
```

**Comment by macalinao** [comment]
Nvm, I am just changing my code to use `JsonObject` instead. Thanks!
