### ISSUE TITLE
More generic Fetcher

### ISSUE THREAD

**Issue by nightscape** [sangria-graphql/sangria#397]
Imagine a (simplified) case like the following:
I want to retrieve data via a `Fetcher`. The data structure I use to perform the fetching (the `Id` type variable) looks something like this:
```scala
case class FilmRequest(id: Int, categoryId: Int) extends Deferred[FilmResponse]
```
Both the film id and the category id are required to fetch the data, but the response contains only film ids and no category ids:
```scala
case class FilmResponse(id: Int, title: String)
```
This means, that it's impossible to write a _stateless_ `HasId[FilmResponse, FilmRequest]` instance.
It would be possible to write a _stateful_ instance that contains a `Map[Int, FilmRequest]` and use that to look up the original `FilmRequest`, but that means that I have to know all `FilmRequest`s before constructing this stateful `HasId` instance, which in my case doesn't work.

I propose to change Fetcher in the following way:

1. Rename the `Id` type variable to `Request` or `Req`.
2. Replace the current `idFn: Res => Id` with two functions `resultIdFn: Res => Any` and `requestIdFn: Req => Any = identity`. If `requestIdFn` gets added as last argument with a default value, this shouldn't break existing code.
3. In all places where `idFn` was used to lookup the request/id for a response, use the id value calculated by `resultIdFn` and `requestIdFn` to do the lookup (via some cache `Map`s).

A more type-safe way to do this would be to give `Fetcher` both a `Req` and an `Id` type parameter and use `resultIdFn: Res => Id` and `requestIdFn: Req => Id`.
The additional type parameter will require more code changes though.

**Comment by OlegIlyenko** [comment]
Thanks for a detailed description! I would like to better understand your scenario. Does the interdependence between film ID and category ID means that film ID is only unique within specific category?

I also wonder whether you have already looked at relation fetchers? Based on your description, it looks like this is something that might be used for this scenario.

**Comment by nightscape** [comment]
So the actual use-case is from my PR to your `graphql-gateway` project:
https://github.com/OlegIlyenko/graphql-gateway/pull/6
I just thought I'd simplify the problem to a minimalistic example.
Maybe we can continue the discussion over there and see if this is still required then.
I'm also checking out relation fetchers more thoroughly. I can't tell yet if they solve the problem.

**Comment by nightscape** [comment]
I've been pondering `Fetcher`s and if they solve this problem, but I think they don't.
Sticking with the film example mentioned above:
Let's say I'm querying an external movie REST service.
I can request a movie using `GET /category/123/film/456` which will return the following JSON response:
```json
{
  "id": 456,
  "title": "Tasty Summer Drinks"
}
```

The film id `456` is globally unique, so not dependent on the category id, but the response just doesn't return the category id.
There is no route to request a film without the category id (which might be considered a bad practice, but let's assume this is not under our control).
Afais, neither `Fetcher.apply` nor `Fetcher.rel` would work with this use-case because both require a
```scala
fetch: (Ctx, Seq[FilmRequest]) ⇒ Future[Seq[FilmResponse]]
```
along with a
```scala
new HasId[FilmResponse, FilmRequest] {
  def id(value: FilmResponse): FilmRequest = ???
}
```
which one can't provide because the information in `FilmResponse` is insufficient to create a `FilmRequest`.

The actual use case in https://github.com/OlegIlyenko/graphql-gateway/pull/6 is a little more involved, but boils down to the same problem.

**Comment by OlegIlyenko** [comment]
Given these 2 constraints you've mentioned:

* I can request a movie using GET /category/123/film/456
* The film id 456 is globally unique

We can assume context look like this:

```scala
class Ctx {
  // loads data via HTTP with `GET /category/<CATEGORY_ID>/film/<FILM_ID>`
  def getFilmByCategoryAndFilmId(req: FilmRequest): Future[FilmResponse] = ???

  // other stuff...
}
```

In this case you can use relations to define film `Fetcher` like this:

```scala
val FilmByCategoryAndFilmId = Relation[FilmResponse, (FilmRequest, FilmResponse), FilmRequest](
  "byCategoryAndFilmId", tmp ⇒ Seq(tmp._1), _._2)

Fetcher.relOnlyCaching[Ctx, FilmResponse, (FilmRequest, FilmResponse), Int](
  (ctx, relIds) ⇒ {
    val ids: Seq[FilmRequest] = relIds(FilmByCategoryAndFilmId)
    val results = ids.map(req ⇒ ctx.getFilmByCategoryAndFilmId(req).map(req → _))

    Future.sequence(results)
  })(HasId(_.id))
```

Do you think this might work in your scenario? (sorry, haven't yet looked in detail at the graphql-gateway PR, was a bit busy recently)

**Comment by nightscape** [comment]
Hi @OlegIlyenko,

the tuple trick is nice. I think that should work.
Closing this issue now, should it not work I'll reopen it.

Thanks for your help!
