### ISSUE TITLE
how to return good http error code in case of error

### ISSUE THREAD

**Issue by winguse** [sangria-graphql/sangria#405]
check the code in the document: https://sangria-graphql.org/learn/#error-handling . It's really good to return BadRequest for user errors.

> When some unexpected error happens in the resolve function, sangria handles it according to the rules defined in the spec. 

This works as the document described, but the status code is 200 (OK), which sounds not that perfect.

And, if I implement my custom ExceptionHandler, those errors I handle will be in the `.map(Ok(_))` as well.

Is there any way to improve this?

**Comment by OlegIlyenko** [comment]
As mentioned in the example from mentioned section of the documentation, you can map various exceptions to different HTTP status codes:

```scala
executor.execute(query, ...)
  .map(Ok(_))
  .recover {
    case error: QueryAnalysisError ⇒ BadRequest(error.resolveError)
    case error: ErrorWithResolver ⇒ InternalServerError(error.resolveError)
  }
```

In addition, you can use extended [execution scheme](https://sangria-graphql.org/learn/#alternative-execution-scheme) with following import:

```scala
import sangria.execution.ExecutionScheme.Extended
```

This will give you not only the resulting JSON, but also additional information about exceptions that happened along the way. You can use this information to return an HTTP code other than 200 `Ok(_)`.

**Comment by winguse** [comment]
Good read and it's really help, thank you!
