### ISSUE TITLE
Fetchers don't receive updated context

### ISSUE THREAD

**Issue by christianharrington** [sangria-graphql/sangria#413]
When using `UpdateCtx`, it seems like the updated context isn't passed to `Fetcher`s when resolving any `Deferred` values. This is true both for queries and mutations.

Example:
```scala
import sangria.schema._
import sangria.execution._
import sangria.execution.deferred._
import sangria.macros._
import sangria.marshalling.circe._

import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.duration.Duration
import scala.concurrent.{Await, Future}

implicit val hasId: HasId[Boolean, Int] = _ => 1
val fetcher = Fetcher[Boolean, Boolean, Int]((ctx, ids) => Future(ids.map(_ => ctx)))

val NestedType = ObjectType(
  "Nested",
  fields[Boolean, Unit](
    Field("value", BooleanType, resolve = ctx => ctx.ctx),
    Field("fetcher", BooleanType, resolve = _ => fetcher.defer(1))
  )
)

val QueryType = ObjectType(
  "Query",
  fields[Boolean, Unit](
    Field("fetcher", BooleanType, resolve = _ => UpdateCtx(fetcher.defer(1))(_ => true)),
    Field("nested", NestedType, resolve = _ => UpdateCtx(Value(()))(_ => true))
  )
)

val schema = Schema(QueryType)

val query = graphql"{ fetcher nested { value fetcher }}"

val resolvers = DeferredResolver.fetchers(fetcher)

val ctx = false
val result = Executor.execute(schema, query, ctx, deferredResolver = resolvers)

println(Await.result(result, Duration.Inf).spaces2)
```

This prints:
```json
{
  "data" : {
    "fetcher" : false,
    "nested" : {
      "value" : true,
      "fetcher" : false
    }
  }
}
```

I would expect all the fields to resolve to `true`. I first ran into this in Sangria 1.4.1, but it also happens in 1.4.2. I haven't checked earlier versions.

**Comment by OlegIlyenko** [comment]
Deferred values are collected from multiple fields during the execution. They might also come from different nesting levels. By the time these deferred values are given to a fetcher, potentially multiple context objects were involved to produce them. So it is not trivial to decide which one should be given to a fetcher/`DeferredResolver`. To avoid ambiguity, fetcher/`DeferredResolver` always given the initial context object, so `UpdateCtx` does not have influence that context object.

**Comment by christianharrington** [comment]
That makes sense, but it seems like it drastically limits the usefulness of `UpdateCtx`. For example, the [Resolve-Based Auth example][resolve-example] on the website wouldn't work if any of the later fields were resolved using fetchers (and required authentication).

The specific issue I am trying to resolve has to do with using read replicas. In the schema I am working on, we have several mutations that return objects, that in turn have fields that use fetchers. To avoid issues due to replica lag, we wanted to set a flag in the context instructing all subsequent reads to use the master database.

Given the current behavior I can't see any way to achieve this without using some kind of shared mutable state, which I would very much like to avoid.

> To avoid ambiguity, fetcher/DeferredResolver always given the initial context object, so UpdateCtx does not have influence that context object.

A way to avoid this ambiguity would be to treat deferred values with different contexts as *distinct*. E.g. `fetcher.defer(1)` with a context `A` would be fetched separately from `fetcher.defer(1)` with context `B`. This could lead to the same value being fetched multiple times, but I would argue this is reasonable, since the result might depend on the context (as it does in my use case).

I couldn't find any mention of the current behavior in the documentation. Want me to open a PR that makes a note of it?

[resolve-example]: https://sangria-graphql.org/learn/#resolve-based-auth

**Comment by ahmedlhanafy** [comment]
@christianharrington Did you end up finding a solution for this problem?
