### ISSUE TITLE
argOpt returns unexpected type at runtime

### ISSUE THREAD

**Issue by cneijenhuis** [sangria-graphql/sangria#434]
Given an argument like this:

```scala
val OptionalStringArg: Argument[Option[String]] = Argument("foo", OptionInputType(StringType))
```

I'd expect that argOpt returns `Option[Option[String]]`. The compiler also thinks so, however at runtime I get `Option[String]`.

```scala
val t1: Option[Option[String]] = ctx.argOpt(OptionalStringArg)
val t2: Option[String] = ctx.argOpt(OptionalStringArg) // Does not compile

println(t1) // prints "Some(foobar)", instead of the expected "Some(Some(foobar))"
```

I believe this `instanceOf` is to blame: https://github.com/sangria-graphql/sangria/blob/master/src/main/scala/sangria/schema/Context.scala#L301

**Comment by paulpdaniels** [comment]
I'm not sure that type of argument makes much sense in GraphQL, what would the schema for an option of an option of a string look like?

**Comment by cneijenhuis** [comment]
Right, it looks a little strange without context 😉 I wanted to use this inside a middleware. The middleware is called for any field, including fields that don't have this argument declared in the schema. Therefore:

* `None` - the field does not have the argument
* `Some(None)` - the field has the argument, but it was not set

I don't really need that distinction, but I can't call `arg()` instead of `argOpt()` because it will throw an exception in the first case.

My workaround is to first check if the field has the argument at all, and only if so, call `arg()`.
