### ISSUE TITLE
Moving forward with Sangria

### ISSUE THREAD

**Issue by yanns** [sangria-graphql/sangria#446]
Please read the following before: https://github.com/sangria-graphql/sangria/issues/445

With great sadness, the Sangria community will have to organize itself and continue development without Oleg Ilyenko in the future.
This thread exists to discuss how to move forward after we’ve processed the sad news. There is no reason to rush this, please take your time.
We at commercetools, where Oleg has worked since 2013, are using Sangria extensively and are invested in its future.

Let's open the discussion on how to maintain Sangria in the future.

**Comment by yasserkaddour** [comment]
I am the only remaining member in sangria-graphql organization, unfortunately I only have write access for 2 repos https://github.com/sangria-graphql/sangria-playground and https://github.com/sangria-graphql/sangria-relay-playground . Your colleague @cneijenhuis told me he already contacted GitHub on how to regain full access to the organization and apparently it's a lengthy process. I would be happy to help appoint worthy maintainers for Sangria to continue the work, like Oleg would have liked.

**Comment by yanns** [comment]
For information, we are in contact with Github to check if we can gain write access to the whole organization and the related projects.
I'll keep you informed.

**Comment by yanns** [comment]
I guess they are other parts we have to check:
- DNS: sangria-graphql.org
- rights to push new release (sonatype / maven): https://github.com/sangria-graphql/sangria/blob/65ffe26e4e2f01ded45520e6e872414f9349c7d4/build.sbt#L59-L66

**Comment by dave-handy** [comment]
@yanns do you know anything about the "scaldi" org and projects? I don't think these are nearly as popular or active as sangria, but they do need some basic care and feeding to keep up with dependency and scala language updates. My (small) company is heavily invested in the scaldi core library, and might be willing to take on some of the responsibility.

Any tips? I am thinking about making a similar issue to this one in the scaldi repo and see if someone chimes in with helpful information. However I'm not expecting much in response since it is much less active.

I'm assuming Oleg developed scaldi during his tenure at your company, but you don't use it there any longer?

**Comment by yanns** [comment]
@dave-handy we are in the process of having all rights on all projects, included scaldi.
This is the first step.
In a second step, I'd like to make a call for people who are willing to maintain those, and give them enough rights to do so.

You can open a similar issue on scaldi. If you already volunteer to maintain the project, please mention it also.(it'd be very welcome ❤️ )

**Comment by vmandrychenko** [comment]
Hello everyone,

We ([Garner](https://www.garnercorp.com)) don't have the resources to maintain the sangria repo full time but we will certainly contribute with PRs, new features, bug fixes and an increase of the code coverage, especially if it aligns with our feature/bugfix road map.

**Comment by paulpdaniels** [comment]
I know the team at [LeadIQ](https://github.com/leadiq) would very much like to contribute to Sangria's continued success. I personally would be interested in helping maintaining Sangria, but I'm not sure how much use I would be since I haven't ever really messed with the internals of the library itself. 

Perhaps we could start by going down the list of top contributors and seeing if they would be interested in being a co-maintainer? Then we can start refining the contribution process from there?

**Comment by anagrius** [comment]
We [Humio](https://www.humio.com) are also very invested in Sangria and would like to help out as possible.

**Comment by jregistr** [comment]
Not sure if this has ever been raised in the history of Sangria, but could [Scala Center](https://scala.epfl.ch/) or [Lightbend](https://www.lightbend.com/) be the folks we are looking for? It's looking so far that even though we have many contributors, we still lack a someone willing to be maintainer. With Sangria being THE GraphQl implementation in Scala, it'd make sense for one of these large organizations to lead it. Or is that not how that works?

**Comment by dave-handy** [comment]
@yanns has there been any progress on getting the needed permissions? I see that there hasn't been any new commits in sangria master either.

**Comment by yanns** [comment]
Some news:
- we opened on ticket on github to gain the rights as they asked
- after several weeks of silence, they finally answered us, and it's more complicated than what they initially told us 🙄 
- we may need more papers from the family

So we'll try that and keep you in touch.
But all in all, github is not very cooperative on that and making everything complex.

**Comment by dave-handy** [comment]
Thanks for the update! Protenus may start a fork of scaldi if we decide to start our scala 2.13 process soon.

**Comment by siderakis** [comment]
I started hacking around with the idea of [converting a schema created using Sangria to a GraphQL-Java schema](https://github.com/siderakis/sangria-graphql-java). The end result would be similar to [kotlin-graphql](https://www.kotlinresources.com/library/graphql-kotlin).

For me this seems like a fine option but I'm wondering what others think. I'm a little biased because I work on [rejoiner.io](https://rejoiner.io) which is also based on [GraphQL-Java](http://graphql-java.com).

**Comment by travisbrown** [comment]
@yanns Is there anything any of us can do to help with this process?

**Comment by yanns** [comment]
@travisbrown If you know some intern at github, maybe this person could help our case.
Otherwise I still have to take the time to prepare new papers with the family.

**Comment by schrepfler** [comment]
I’ve pinged Nat Friedman on Twitter if they can take a look. https://twitter.com/schrepfler/status/1159262893919145984?s=21

**Comment by TJSomething** [comment]
Would it make sense to do work on a temporary fork while the process is being worked out?

**Comment by travisbrown** [comment]
@TJSomething Publishing to Maven Central via Sonatype also [depends on access to the GitHub organization](https://issues.sonatype.org/browse/OSSRH-48782) (although it's possible that @yasserkaddour could get verified now via [sangria-playground](https://github.com/sangria-graphql/sangria-playground)).

There is ongoing work happening in forks (I'm personally testing local builds for Scala 2.13 now, for example). I'm not a core maintainer, but my own feeling is that the overhead of switching to a temporary "official" fork would be substantial, and we should avoid it if we can, even if it means waiting a little longer for new official releases.

**Comment by nickhudkins** [comment]
Hi @yanns anything we can do to help out?

**Comment by yanns** [comment]
@nickhudkins not that I'm aware of, unless you know someone at Github who can help us here.
I send them a document, and I'm still waiting for their answer...

**Comment by nickhudkins** [comment]
Thanks @yanns, I reached out to some folks on twitter in hopes of moving this along, and at least have a party willing to help. I am happy to do the leg work to help you out if you need anything, including just sending emails and talking to people :). Hopefully we can keep Oleg's work alive and well right here in the `sangria-graphql` org.

**Comment by nickhudkins** [comment]
We may have an answer sooner thanks to: https://twitter.com/TwitterOSS/status/1171190354642497537 ?

**Comment by DEGoodmanWilson** [comment]
@yanns GitHub employee here, although not one in a direct position to help. Can you shoot me an email DEGoodmanWilson@github.com ?

**Comment by mjadczak** [comment]
Given that this has now been a pending issue for nearly 5 months, with no resolution seemingly in sight, should there now be a serious conversation about how long we are prepared to wait for the bureaucratic machine to grind through this issue, and at what point setting up an "official" fork (temporary or otherwise) should be considered?

**Comment by bengraygh** [comment]
> There is ongoing work happening in forks (I'm personally testing local builds for Scala 2.13 now, for example). I'm not a core maintainer, but my own feeling is that the overhead of switching to a temporary "official" fork would be substantial, and we should avoid it if we can, even if it means waiting a little longer for new official releases.

Do you still feel this way, @travisbrown ?

I agree with @mjadczak that the uncertainty needs to be addressed. Was there any update from github after the documentation they requested, @yanns ?

I think we all agree that sangria is an important and popular project in dire need of maintenance. The longer this issue remains unresolved, the more people will turn away from this library, to the detriment of the community.

@jregistr proposed new custodianship of sangria in June, although it doesn't appear that Scala Center or Lightbend have expressed an interest in doing so. It seems that the largest corporate user of sangria, and therefore the most resourced to maintain it, is twitter. Would it make sense to propose an official twitter fork and direct community efforts there? With twitter OSS behind it, the project would probably be more actively maintained and widely adopted.

**Comment by yanns** [comment]
> > There is ongoing work happening in forks (I'm personally testing local builds for Scala 2.13 now, for example). I'm not a core maintainer, but my own feeling is that the overhead of switching to a temporary "official" fork would be substantial, and we should avoid it if we can, even if it means waiting a little longer for new official releases.
> 
> Do you still feel this way, @travisbrown ?
> 
> I agree with @mjadczak that the uncertainty needs to be addressed. Was there any update from github after the documentation they requested, @yanns ?

Yes we provided the documentation they requested.
After some time without news, I asked them about the status, and they answered that they need more documentation.

Github is not really helping here. Every time we provide something, they ask for something more. 😢 

So we have to ask the mother, one more time...
To be honest, we are feeling demotivated by the lack of any progress compared to the amount of time / energy we put into it.

If an organization or someone is ready to have an official fork, I'd also be ready to help.

**Comment by bengraygh** [comment]
> Yes we provided the documentation they requested.
> After some time without news, I asked them about the status, and they answered that they need more documentation.
> 
> Github is not really helping here. Every time we provide something, they ask for something more. 😢
> 
> So we have to ask the mother, one more time...
> To be honest, we are feeling demotivated by the lack of any progress compared to the amount of time / energy we put into it.

This is really disappointing from github. It is not fair to expect a grieving mother to keep signing more documents. There must be some way we can send this up the chain.

Thank you for what must be draining work, @yanns .

**Comment by travisbrown** [comment]
@yasserkaddour Would you be willing to help with the Sonatype verification, so that the publication coordinates don't have to change, even if the GitHub organization does? We'd just need to create a file named `OSSRH-48782` in the sangria-playground repo: https://github.com/sangria-graphql/sangria-playground/pull/20

**Comment by travisbrown** [comment]
I think we should consider moving to a new GitHub organization, at least temporarily. GitHub might be willing to work with us to recover an unused account name (I've had luck with this in the past, and it's been relatively fast—a couple of days, not months), so `https://github.com/sangria` might be an option, or something like `sangria-scala` or `sangria-graphql-org` (both of which are currently available).

If we're able to recover access to the `org.sangria-graphql` group ID, then we could publish from forks in this organization and there would only be some small overhead for maintainers, but none for adopters.

**Comment by jregistr** [comment]
>  Would it make sense to propose an official twitter fork and direct community efforts there? With twitter OSS behind it, the project would probably be more actively maintained and widely adopted.

I honestly agree with @bengraygh here. Has anyone here contacted anyone from or has connection to Twitter OSS? Finatra and all the other projects twitter is behind are well maintained so their involvement in this project would be amazing.

**Comment by travisbrown** [comment]
@jregistr Yes, we've [heard from someone at Twitter](https://twitter.com/TheGreenJohnny/status/1171828866219790337):

> Thanks for the heads up. We (Sangria-using friends at Twitter) are interested in figuring this out. I'll start some conversations.

…but that was in the context of working with GitHub to get access to the organization here.

I don't know much about how things currently work at Twitter OSS, but I was on the team a few years ago, and I think it's unlikely that Twitter would adopt the project in the sense you're talking about. I also don't think that's necessary, though—there are plenty of contributors and potential maintainers, the issue is just GitHub making this transfer difficult.

**Comment by sachee** [comment]
@travisbrown @yanns @jregistr Hey! This is Sasha from Twitter (I work on the team that works with GraphQL/Sangria). We would love to set something up and talk about what that general situation with the project is and see what we can do to help.

**Comment by felipesilva** [comment]
@sachee @travisbrown @yanns I sent you an email so we can get this going.

**Comment by yanns** [comment]
Status update:

we had a meeting with @felipesilva @sachee @travisbrown and others. It was great to see you!

We still would like to have access to the organization. 
-> I'm checking for the papers github is asking for. I'll update this issue if I have news.

@travisbrown opened a [PR](https://github.com/sangria-graphql/sangria-playground/pull/20) so that we could be allowed to push to sonatype. For the moment, only @yasserkaddour has the permissions to merge it.

**Comment by travisbrown** [comment]
Thanks for the update, @yanns! As I mentioned in the call, I'm also [checking with Sonatype](https://issues.sonatype.org/browse/OSSRH-48782?focusedCommentId=850021&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-850021) about alternative ways to get access to the `org.sangria-graphql` group ID, so that we don't have to change the Maven Central coordinates even if we do end up deciding (possibly temporarily) to use "official" forks on GitHub.

**Comment by yasserkaddour** [comment]
I merged the PR, sorry for the delay

**Comment by travisbrown** [comment]
@yasserkaddour Thank you! I've commented on the Sonatype issue with a link to the file.

**Comment by yanns** [comment]
Thx a lot @yasserkaddour!

**Comment by travisbrown** [comment]
We've now published new releases of nine of Sangria's modules with Scala 2.13 support, as well as a first 2.0.0 milestone release of Sangria itself:

* https://github.com/sangria-graphql-org/sangria/releases/tag/v2.0.0-M1

I've published GitHub release notes for all ten repos, but some still need CHANGELOG and README update PRs.

There are eight other modules (listed [here](https://github.com/sangria-graphql/sangria/issues/440)) that still need 2.13 PRs. I might not be able to get to these for a couple of weeks, so any help would be appreciated.

**Comment by yanns** [comment]
Small update: we still haven't been granted access by Github. We are still in the process.

**Comment by yanns** [comment]
I'm now an owner of https://github.com/sangria-graphql 🥳 
We now have to replay all changes done on the fork https://github.com/sangria-graphql-org

**Comment by zvuki** [comment]
@yanns great news! Do you mind sharing the ownership with someone, you know, just in case?
p.s. I wish you good health.

**Comment by yanns** [comment]
> @yanns great news! Do you mind sharing the ownership with someone, you know, just in case?
> p.s. I wish you good health.

of course. We have to [avoid being a single point of failure](https://yanns.github.io/blog/2020/02/11/open-source-and-sole-maintainers/).
And I'll need help maintaining all the repositories.

**Comment by travisbrown** [comment]
Wow, this is great news, @yanns!

**Comment by yanns** [comment]
update:
I've replayed all changes made on the temp organization to this one

In the short term, I'd like to add at least one other owner to be on the safe side.
Any volunteer?

**Comment by travisbrown** [comment]
@yanns I probably won't have much time to help with maintenance in the immediate future, but I'd be happy to join as a backup (and I already have `org.sangria-graphql` publishing rights on Sonatype).

**Comment by yanns** [comment]
> @yanns I probably won't have much time to help with maintenance in the immediate future, but I'd be happy to join as a backup (and I already have `org.sangria-graphql` publishing rights on Sonatype).

Thanks you very much for proposing. I added you as backup.
Now the project is quite safe from this perspective.

**Comment by sachee** [comment]
@yanns let me know if we (Twitter) can be of any help here. We have time set aside to help if you need it.

**Comment by yanns** [comment]
For the moment, I'm maintaining the sangria ecosystem with minimal time investment.

I'm not pushing sangria forward, like checking for new GraphQL features and implementing them.
I don't spent much time on opened issues.
I review PR as they come.

I will not be able to spend more time on it.

I think there are different kind of help I'd need:

- someone taking care of the [website](https://sangria-graphql.org/). I don't know how the [website](https://github.com/sangria-graphql/sangria-website) is published. I don't know if Oleg bought the domain, for how long...
- some people motivated to push sangria forwards, invested in the GraphQL community as well, checking for new features on the GraphQL side...
- some people fixing open issues
- some people checking for open issues, reviewing pull requests...

I think checking the website is a top priority to avoid losing the domain.

**Comment by astolzenberger** [comment]
Regarding the domain sangria-graphql.org

Updated Date: 2018-09-25T18:52:13Z
Creation Date: 2015-07-28T21:48:18Z
Registry Expiry Date: 2020-07-28T21:48:18Z

**Comment by virtualirfan** [comment]
Just reserved sangria-graphql.dev and sangria-graphql.com in case those are needed.

**Comment by mikulskibartosz** [comment]
Hi, is there an open issue that would be a good starting point for someone who has not contributed to that project yet?

**Comment by yanns** [comment]
> Hi, is there an open issue that would be a good starting point for someone who has not contributed to that project yet?

not that I'm aware of. I won't have the time to do that.

**Comment by sachee** [comment]
Hey @yanns thanks for all the info.

Twitter has headcount to help out with PRs, fixing issues, etc. Will we need any special permissions to contribute/review PRs?

**Comment by yanns** [comment]
@sachee Thanks for proposing! Very much appreciated.
I've created a team that has write access to all repositories: https://github.com/orgs/sangria-graphql/teams/contributors

We can discuss there who I should add.

**Comment by sachee** [comment]
hey @yanns I get a 404 from the link you posted, do you have another link?

**Comment by yanns** [comment]
> hey @yanns I get a 404 from the link you posted, do you have another link?

Maybe the link is only accessible to team members?
We can try another way: can you mention the people I should add to the contributors?

**Comment by sachee** [comment]
Hey @yanns! Here are the Twitter folks who would be interested in contributing:
@lostplan
@nicky-isaacs
@mgadda
myself (@sachee)

**Comment by yanns** [comment]
> Hey @yanns! Here are the Twitter folks who would be interested in contributing:
> @lostplan
> @nicky-isaacs
> @mgadda
> myself (@sachee)

💯 
You are all invited to the "contributors" team

**Comment by yanns** [comment]
About the DNS domain: https://github.com/sangria-graphql/sangria-website/issues/74

**Comment by Crisp3333** [comment]
Hello, I would love to help contribute if needed that is. I depend on Sangria a lot for work.

**Comment by yanns** [comment]
> Hello, I would love to help contribute if needed that is. I depend on Sangria a lot for work.

Great to hear!
do you already have an idea?
If not, you can start looking at existing PR and/or issues, reviewing them.
https://github.com/sangria-graphql/sangria-website/issues/74 is also an issue that one should take care of.

**Comment by Crisp3333** [comment]
Not much idea, but I will take your advise and look into PR and the issue you pointed out.

**Comment by yanns** [comment]
Sangria is now maintained by some people.
Thanks a lot to @nickhudkins @sh0hei @xsoufiane for your help.
If you want to join the efforts, please talk to us on https://gitter.im/sangria-graphql/sangria-dev
