### ISSUE TITLE
Fetcher caching

### ISSUE THREAD

**Issue by rvanheest** [sangria-graphql/sangria#447]
https://sangria-graphql.org/learn/#caching says that "_every query execution gets its own isolated cache instance._". Can someone explain how this works with the given example? Who is responsable for clearing the cache after each query? I don't see that happening anywhere in the Sangria code base, neither do I see this reflected in the functioning of my experimentation with GraphQL and Sangria.

Is the documentation in https://sangria-graphql.org/learn/ assuming that for every query I receive on my GraphQL servlet route, I have to create a new instance of my `Schema`, `DeferredResolver`, `Fetcher`s and `FetcherCache`s? Because that is NOT what I'm doing. With the booting of my service I instantiate the servlet route and the whole `Schema`, `DeferredResolver`, etcetera once and then use these instances on every query that comes in.
With that setup I don't see how the caches that I'm now linking to my `Fetcher`s get cleared after each query.

Practical example:
* query for `X`
* mutate `X`
* query for `X` again should yield the new value. However, with the cache in place I still get the old value...

**Comment by schneiderlin** [comment]
cache instance is in DeferredResolver's queryState,
for every query, Executor.execute will re-init deferredResolver's queryState.
https://github.com/sangria-graphql/sangria/blob/0bf80537e838e6ace9952521b57dcf3f05903e1c/src/main/scala/sangria/execution/Executor.scala#L131
    
you don't have to create a new instance of Schema and DeferredResolver for every query,
they are reuse, but resolver's state is reset by Executor
