### ISSUE TITLE
Sangria schema running on GraphQL-Java

### ISSUE THREAD

**Issue by siderakis** [sangria-graphql/sangria#452]
I'm thinking about starting a small library that would allow developers to port their Sangria schemas to run on top of GraphQL-Java with minimal effort.

This would result in an architecture similar to https://github.com/ExpediaDotCom/graphql-kotlin

This would allow us to get the new feature of GraphQL ([@defer directive](https://www.graphql-java.com/documentation/v12/defer/), etc) while using the same Sangria API for creating the schema.

Just an idea at the moment, any feedback would be appreciated.

**Comment by siderakis** [comment]
Something like this would get the basic schema translated to the Java framework. The difficult part will be mapping the DataFetchers/Resolvers/DataLoaders.

```
def scalaToJavaSchema(scalaSchema: Schema[Any, Any]): graphql.schema.GraphQLSchema = {
    val query: GraphQLObjectType = scalaToJavaObject(scalaSchema.query)
    val schemaBuilder = GraphQLSchema.newSchema().query(query)
    scalaSchema.mutation.foreach(mutation => schemaBuilder.mutation(scalaToJavaObject(mutation)))
    schemaBuilder.build()
  }

  private def scalaToJavaObject(objectType: ObjectType[Any, Any]): GraphQLObjectType = {
    val queryBuilder = GraphQLObjectType.newObject()
    objectType.description.foreach(queryBuilder.description)
    objectType.fields.foreach(scalaField => {

      val fieldBuilder =
        GraphQLFieldDefinition.newFieldDefinition().name(scalaField.name)

      scalaField.deprecationReason.foreach(fieldBuilder.deprecate)
      scalaField.description.foreach(fieldBuilder.description)

      fieldBuilder.dataFetcher(env=>{
        // TODO: fix me
        scalaField.resolve(env)
      })
      scalaField.arguments.map(

        scalaArg => {
          val argBuilder =
            GraphQLArgument.newArgument().name(scalaArg.name)

          scalaArg.defaultValue.foreach(argBuilder.defaultValue)
          scalaArg.description.foreach(argBuilder.description)

        }
      )
      queryBuilder.field(fieldBuilder.build())
    })
    queryBuilder.build()
  }

```

**Comment by nickhudkins** [comment]
Hey @siderakis, we're pretty limited on maintainers as it is, so I suspect this falls outside the scope of something as an organization we'd like to take on, but it certainly sounds like an interesting approach! While I'd much prefer a PR to add @defer directive support into Sangria, I'd be excited to see any movement around folks implementing GraphQL servers in Scala!
