### ISSUE TITLE
Split core sangria into modules

### ISSUE THREAD

**Issue by paulpdaniels** [sangria-graphql/sangria#461]
Currently the sangria core package includes everything needed to start working with sangria on the server side. However, there are cases where this seems to be overkill like with the drunk client. I propose splitting the core module into several sub modules that will continue to live here. For ease of use we’d continue to export the core module which would contain all modules but would allow consumers to pick more specific modules depending on their needs. My thought is:

- sangria (aggregate)
- sangria-execution (Executor/reducers)
- sangria-derived (macros and derivation)
- sangria-ast (The schema ast)
- sangria-parse (just the ast parsing)

The advantage here is that the parse module could be exchanged with a different parser, clients only need ship with a hard dependency on the ast. And lib developers can explore different execution models while still relying on solid foundations.

**Comment by performantdata** [comment]
There is now [a `sangria-ast` library](https://search.maven.org/search?q=g:org.sangria-graphql%20a:sangria-ast_2.13).

**Comment by performantdata** [comment]
There is now [a `sangra-parser` library](https://search.maven.org/search?q=g:org.sangria-graphql%20a:sangria-parser_2.13).

**Comment by yanns** [comment]
This is now a [sangria-derivation library](https://search.maven.org/artifact/org.sangria-graphql/sangria-derivation_2.13)
I don't think we will introduce more modules.
