### ISSUE TITLE
Federation support

### ISSUE THREAD

**Issue by hnrklssn** [sangria-graphql/sangria#462]
Is there any plan to support Apollo Federation?

**Comment by ErikHedblom** [comment]
I'm also interested in this and would be happy to contribute.

I've done some experimentation and the the main issue I'm facing is the `_entities` resolver. Currently it looks like this:

```scala
implicit ctx => Action.sequence[Ctx, Option[Any]](ctx.arg[Seq[JsValue]]("representations").map(getEntity))
```
and getEntity has this signature:
```scala
def getEntity(data: JsValue)(implicit ctx: Context[Ctx, _]): LeafAction[Ctx, Option[Any]]
```

This works as long as I don't have any `DeferredValues`, if I do, I run in to this issue #465.

**Comment by joshjones95** [comment]
Hi,

Has there been any discussions or packages that have started to support this for sangria?

**Comment by paulpdaniels** [comment]
It is possible to do, we have an internal implementation of it that we use for our services. The main issue that the marshallers need to be changed to support object scalars.

**Comment by yanns** [comment]
@paulpdaniels we would also be interested in that.
As far as I can understand you, it's not possible to support federation with a "simple" library.
Some more deeper changes are needed?

**Comment by paulpdaniels** [comment]
@yanns The spec itself is purely additive and can be put on top of the existing implementation. You need to add some new directives and probably some sugar to make them easy to add. But then the only change is that you need to basically wrap your existing schema with something like:

```scala
def federate[Ctx, Val: ClassTag](_schema: Schema[Ctx, Val], resolvers: EntityResolver[Ctx]*): Schema[Ctx, Val]
```

Where `EntityResolver` looks something like this:

```scala
trait EntityResolver[Ctx] {
  def typename: String

  def resolve(obj: JsObject): LeafAction[Ctx, Option[Any]]
}
```

I'll see if I can extract a gist of what we are doing. The incompatibility comes from the fact that the existing marshallers won't support the `_Any` scalar that federation needs. So we had to forked our own, basically: [here](https://github.com/sangria-graphql/sangria-play-json/blob/master/src/main/scala/sangria/marshalling/playJson.scala#L72) and [here](https://github.com/sangria-graphql/sangria-play-json/blob/master/src/main/scala/sangria/marshalling/playJson.scala#L61) need to be amended to accept the `ObjectNode` of the marshaller.

**Comment by paulpdaniels** [comment]
Here we go: https://gist.github.com/paulpdaniels/f6e637d1bbbd67d13ec661a7306e6af4

**Comment by ErikHedblom** [comment]
I've been using the same approach but I'm running into this  https://github.com/sangria-graphql/sangria/issues/465 when the entity resolver doesn't return a deferred value but the entity has has nested deferred fields. Other than that this is working well for me.

**Comment by paulpdaniels** [comment]
Interesting, haven't encountered that @ErikHedblom , though we still have a relatively small interplay of our federated services. Yeah the `LeafAction` is decidedly not great, there is probably someway to improve that syntax but will need some work on the internals I think.

**Comment by yanns** [comment]
Should I create a new repo under the sangria organization for that?
We could mark the library as "alpha" first.

**Comment by ErikHedblom** [comment]
I think that would be great, we should be able to use @paulpdaniels [gist](https://gist.github.com/paulpdaniels/f6e637d1bbbd67d13ec661a7306e6af4) for the first version.

**Comment by zvuki** [comment]
👋 Is there any progress in this area?

**Comment by yanns** [comment]
You can find the first implementation here: https://github.com/sangria-graphql/sangria-federated/
Please use it with caution and provide feedback.
