### ISSUE TITLE
Guidelines on the thread pool for execute

### ISSUE THREAD

**Issue by surendarchandra** [sangria-graphql/sangria#464]
New to Sangria; what is the general recommendation on how many threads to give to the execution Context? Thanks

**Comment by nickhudkins** [comment]
Hi @surendarchandra this is going to be HIGHLY related to the access patterns of your specific GraphQL server. Do your resolvers do a lot of I/O? Are they CPU bound?

Unfortunately this is going to be something you'll need to deeply understand your applications requirements to be able to provide good guidance here. The default execution context is designed for general purpose workloads, but you'll want to measure. Lots of Non Blocking I/O and plenty of RAM? Give it loads of threads. Lots of CPU bound tasks? Match the virtual cores. This is some pretty hand-wavy guidance but hopefully it points you in the right direction.

The short story is PROFILE PROFILE PROFILE.
