### ISSUE TITLE
ast.Directive vs schema.Directive

### ISSUE THREAD

**Issue by snabar** [sangria-graphql/sangria#467]
Hi! Do you have any examples of creating an ast.Directive. The only examples I can find are of creating a schema.Directive. However, the schema.Field constructor takes a Vector of ast.Directives. Thanks for any help!

**Comment by yanns** [comment]
https://github.com/sangria-graphql/sangria/discussions/913

**Comment by yanns** [comment]
The current API is not very practical.
One has to use `copy` like in https://github.com/apollographql/apollo-federation-subgraph-compatibility/blob/f936cb5e0cbaffe350280aa448f29b57933637c1/implementations/sangria/src/main/scala/graphql/ProductGraphQLSchema.scala#L45

or create some helpers methods like https://github.com/apollographql/apollo-federation-subgraph-compatibility/blob/f936cb5e0cbaffe350280aa448f29b57933637c1/implementations/sangria/src/main/scala/graphql/Directives.scala#L18-L19

I'll work on a [better API](https://github.com/sangria-graphql/sangria/discussions/913)

**Comment by yanns** [comment]
Please check the new API: https://github.com/sangria-graphql/sangria/pull/918/files#diff-591a4b0194f13b7ec4909ee92e958cd2d62707c2c07f2125a12051318cee120cR12-R13
