### ISSUE TITLE
Handling Futures in Middleware

### ISSUE THREAD

**Issue by louisscruz** [sangria-graphql/sangria#469]
I'm currently trying to add some AuthMiddleware following https://sangria-graphql.org/learn/#middleware.

Unfortunately, my specific scenario requires some async requests to be made in order to perform authentication. Because `beforeField` seems to need to return a `BeforeFieldResult`, I'm not sure how to accomplish this without using an `Await.result`:

```scala
object AuthMiddleware extends Middleware[MyRepo] with MiddlewareBeforeField[MyRepo] with MyImplicits {
  override type QueryVal = Unit
  override type FieldVal = Unit

  override def beforeQuery(context: MiddlewareQueryContext[MyRepo, _, _]) = ()

  override def afterQuery(queryVal: QueryVal, context: MiddlewareQueryContext[MyRepo, _, _]) = ()

  override def beforeField(
                            queryVal: QueryVal,
                            mctx: MiddlewareQueryContext[MyRepo, _, _],
                            ctx: Context[MyRepo, _]
  ) = {
    val requiredAuth = ctx.field.tags contains Authorized

    if (requiredAuth) {
      // ensureAuthenticated returns a Future
      Await.result(ctx.ctx.ensureAuthenticated, 5.seconds)
    }

    continue
  }
}
```

Is there a way of doing this in a non-blocking way? Or would you suggest a different approach altogether?

**Comment by paulpdaniels** [comment]
Generally the way we accomplish this is to perform authorization using a QueryReducer instead, usually that is sufficient to reject or accept a request. If you still need to perform authz during the middleware step you would just have the QueryReducer update the context so it could be inspected synchronously from within the middleware

**Comment by louisscruz** [comment]
Oh, interesting! That looks like it’s just what’s needed. I read that section of the documentation but didn’t make the connection. Going to give that a shot.

**Comment by nickhudkins** [comment]
Hey @louisscruz just want to make sure you're all set. If so, perhaps we can add some clarification to the documentation calling out some alternative approaches if you need async auth.

**Comment by louisscruz** [comment]
Yes, that did the trick for me!
