### ISSUE TITLE
ExceptionHandler for *really* unexpected exceptions

### ISSUE THREAD

**Issue by aserrallerios** [sangria-graphql/sangria#473]
First of all, maybe I'm doing something wrong here, but when I use `ExceptionHandler` to capture unexpected exceptions, they all end being returned as regular GraphQL errors, so the only difference I see in using the `ExceptionHandler` is that instead of getting 

```
{"data":null,"errors":[{"message":"Internal server error","path":["units"],"locations":[{"line":2,"column":3}]}]}
```

I get 

```
{"data":null,"errors":[{"message":"blablabla","path":["units"],"locations":[{"line":2,"column":3}]}]}
```

Handled and unhandled failures return 200 http code (as my code transforms "successfull" Futures into 200 responses), and that might be fine with some designs, but I'm wondering if there's any way of making the execution fail as a whole so I can capture it and return a different http code (as it is already possible with `QueryAnalysisError`/`ErrorWithResolver`).

For example, if the database is not available I might want to return a 500 instead of a GraphQL error.

**Comment by yanns** [comment]
What we do:
- we are using the GraphQL errors to be conform to the spec
- on top of that, we check the [error code](https://docs.commercetools.com/api/graphql#error-response-format) and change the HTTP status based on it.
