### ISSUE TITLE
Change context type for a field

### ISSUE THREAD

**Issue by koterpillar** [sangria-graphql/sangria#474]
For code reuse reasons, I have an object type defined as `ObjectType[ContextA, Unit]`. I would like to incorporate this as a field type for an object type defined as `ObjectType[ContextB, Unit]`. I have a function to convert `ContextB` to `ContextA`. How can I convert the context _type_ so I can reuse the type?

**Comment by nickhudkins** [comment]
This is a Scala specific question not Sangria, but generics may help you out here.

```
def objectTypeForAOrB[CtxType] = ObjectType[CtxType, Unit](/* Presumably shared code?*/)

val objectTypeA = objectTypeForAOrB[ContextA]()
val objectTypeB = objectTypeForAOrB[ContextB]()

```

But more importantly... just go repeat yourself, you'll kick yourself later when you need to tear this apart.
