### ISSUE TITLE
Broken Link to example app http://try.sangria-graphql.org in Readme

### ISSUE THREAD

**Issue by hiroki1117** [sangria-graphql/sangria#476]
Hello

I'll check the example qraphql app written with Play framework and Sangria. but **No Such App** page in Heroku.
is This a broken Link. right?

**Comment by muety** [comment]
See https://github.com/sangria-graphql/sangria-playground/issues/21#issuecomment-640237820 :wink:

**Comment by nickhudkins** [comment]
You can see an example here: https://sangria-play-example.herokuapp.com, documentation has been updated to reflect that in other repositories.
