### ISSUE TITLE
Handle Unmarshalling Errors as Bad Request

### ISSUE THREAD

**Issue by pgorin** [sangria-graphql/sangria#479]
Hi!
I have a question. I'm currently using circe as json unmarshaller for graphQl input types. I can see that when a ValueCoercionViolation is thrown due incorrect input types a BadRequest is returned for the given request. I will be glad to know how to reproduce the same behaviour when a custom input type is invalid due a decoding failure. Right now I have a 200 OK response, with null data and the decoding exception materialized under the erros node. I don't know if I'm doing something wrong or this is the expected behaviour. I think that if an input type is incorrectly defined and this situation is during un-marshalling time, the result can perfectly be a Bad Request.

A real example for this situation is having an input type class Validity(from: Date, to: Date), and I must validate that 'to' is always after than 'from'. I'm performing this validation when un-marshalling with circe Decoder the input arguments. I expect that an invalid 'to' can be notified to the client as a Bad Request.
I don't know if I have to use a reducer in order to detect this type of errors of maybe extending a given type of Coercion Exception.

Thank you a lot for your great work.

**Comment by nickhudkins** [comment]
Hi @pgorin this is something that will be specific to your server implementation, as the actual HTTP response is NOT part of the GraphQL spec, so you can do whatever works best for you. 

A similar question was posed here in which I show a possible solution.
https://github.com/sangria-graphql/sangria/issues/524

Hope this helps!
