### ISSUE TITLE
How to use sangria to make a request to an external GraphQL API 

### ISSUE THREAD

**Issue by 1306843** [sangria-graphql/sangria#480]
I need to hit an external API (that is a graphql api) within our service. Does sangria support queries to other endpoints (http) to send a graphql formatted query? I am using Scala with Play. I am new to both Scala and Sangria and GraphQL so if there are some core pieces I am missing please inform. Thank you

```
    val query = graphql"{ 
    account(id: "test") {
    name 
    email
    status {
      verified
    }
   }
  }"

    val result = Executor.execute(schema, query)
val futureResponse: Future[WSResponse] = ws.url(url).post(query)
```

**Comment by nickhudkins** [comment]
Hi @1306843, Sangria is specifically for building GraphQL servers, and as such does not fill the need you are looking for out of the box.

It sounds like you are looking for a GraphQL **client** for scala. There are several options out there, and if you are looking for something built on-top of Sangria: https://github.com/Jarlakxen/drunk is one of those options. There are also other alternatives as well
