### ISSUE TITLE
Expensive suggestions in UnknownTypeViolation 

### ISSUE THREAD

**Issue by agourlay** [sangria-graphql/sangria#497]
While profiling my production system I found out that our application is spending a lot of time building suggestions for error messages in case of unknown type name.

![Screenshot 2020-06-09 at 15 08 29](https://user-images.githubusercontent.com/606963/84151135-353e9700-aa63-11ea-800b-e18462306872.png)

It is possible that an upstream service is hammering the `graphql` endpoint with an invalid query, which is fine 😄 

For all possible types in the schema, the library is running some kind of Levenshtein edit distance computation to propose types with a similar name to the user.

```scala
// KnownTypeNames.scala
      if (!ctx.schema.allTypes.contains(name))
          Left(Vector(UnknownTypeViolation(
            name,
            StringUtil.suggestionList(name, ctx.schema.availableTypeNames),
            ctx.sourceMapper,
            pos.toList)))
        else
          AstVisitorCommand.RightContinue
```

Looking at the code in `StringUtils` for `suggestionList` and `lexicalDistance`, I can see that things can be made a bit faster but deep down I am not convinced it is the right approach.

I think `Sangria` should cache those suggestions as they are expensive to compute especially on big schemas.

One implementation could be to have a `Caffeine` map inside `KnownTypeNames` to keep track of those over time and thus avoiding unnecessary re-computations.

WDYT?

I can prepare a PR if you are interested :)

**Comment by yanns** [comment]
Interesting finding.

This computation is burning CPU right?

My thoughts on that:
- if we assume that a wrongly configured client is sending a query with unknown fields again & again, yes we should have a cache to avoid computing those fields each time.
- this cache should not be used for parts of the schema that are exclusive for one user. For example, one can use schema extensions so that each user can receive a GraphQL schema different from the other ones. Using a cache here would disclosed which fields / types are given to another user. And the results would be wrong.
  -> developers should be able to configure when to use this cache.
- we could also think about being able to disable this feature completely. I don't know for sure, but I don't think it's part of the GraphQL specification.

**Comment by agourlay** [comment]
> This computation is burning CPU right?

Yes :)

> we could also think about being able to disable this feature completely. I don't know for sure, but I don't think it's part of the GraphQL specification.

This is a good point, we just have no idea if Sangria's user are relying on this feature.

> this cache should not be used for parts of the schema that are exclusive for one user

If we use as a cache key

```scala
case class SuggestionCacheKey(input: String, availableTypeNames: List[String])
```

and then for the cache

```scala
val cache = new Cache[SuggestionCacheKey, List[String]]()
```

I believe there will be no data leak issues as the `availableTypeNames` field will enforce the segmentation logicically even if the cache is global.

**Comment by yanns** [comment]
I'm not sure about the leaking.
Let's say that one user can see:
```
{
  attributes {
    ... on MyAtt1 { value }
  }
}
```
and the other can see:
```
{
  attributes {
    ... on MyAtt2 { value }
  }
}
```
would it be possible to cache that we only have the type `MyAtt1` even for the 2nd user?

**Comment by yanns** [comment]
Another idea came to my mind:
- we could try to give suggestions if the failing request is coming from an human
- we could avoid giving suggestions if the failing request is coming from a saved query

For that, we could give the possibility to enable or disable those suggestions on demand:
- for requests coming from GraphiQL for example, we could use http header, user agent or something else to always enable suggestions.
- for other requests, we could disable suggestions.
or
- for other requests:
  - we could first give suggestions, and save into a cache the information that we gave suggestions for this unknown type
  - for the next request with the same unknown type error, we do not give suggestions (using the information from the cache)

**Comment by agourlay** [comment]
Thank you for bringing up many ideas 👍 

> would it be possible to cache that we only have the type MyAtt1 even for the 2nd user?

I do not understand this part, I thought the `SuggestionCacheKey` I proposed earlier would be enough to isolate tenants. Maybe I am missing something, could you please elaborate on how my proposal falls short here?

Also as you mentioned that this is not part of the spec, maybe we could start simply with a global configuration knob to disable this feature entirely on demand. 
This would help me to quickly validate my initial hypothesis regarding the performance issue.

Later we could offer a more fine grained strategy based on the context of the request.

**Comment by yanns** [comment]
I oversaw that `ctx.schema.availableTypeNames` was given into input.
If the cache has this information as a key `(name, ctx.schema.availableTypeNames)` then we should have have any issues.

**Comment by mroach** [comment]
>     * we could also think about being able to disable this feature completely.

This would be a bonus for security reasons. When you have a GraphQL only being used for serving data to your own front-end components for example, suggestions allow attackers to probe the schema. In such setups, you'd want suggestions fully disabled in production.

**Comment by kiranbayram** [comment]
> * we could also think about being able to disable this feature completely.

+1 for this

**Comment by yanns** [comment]
suggestion on how to give the user more control: https://github.com/sangria-graphql/sangria/pull/517

**Comment by yanns** [comment]
https://github.com/sangria-graphql/sangria/releases/tag/v2.0.1
