### ISSUE TITLE
Website seems to be down

### ISSUE THREAD

**Issue by fancellu** [sangria-graphql/sangria#502]
http://sangria-graphql.org

**Comment by lwilli** [comment]
https://github.com/sangria-graphql/sangria-website/issues/74

**Comment by zerodouglas** [comment]
It's been down for a while. For the time being if anyone is interesting, I've pushed it to Netlify.

https://sangria.netlify.app/

**Comment by bengraygh** [comment]
Thank you for doing this. Hopefully, the original domain hasn't been bought by a squatter.

**Comment by grzegorz-bielski** [comment]
The more up to date version of the docs is already available on the: https://sangria-graphql.github.io

**Comment by nickhudkins** [comment]
For the foreseeable future, we'll be using sangria-graphl.github.io as the documentation site. We'll be working through updating documentation across all of the additional libraries, and getting examples of any runnable code deployed.

https://sangria-example.herokuapp.com (Akka HTTP / Sangria)
https://sangria-play-example.herokuapp.com (Play / Sangria)
