### ISSUE TITLE
retire old repo

### ISSUE THREAD

**Issue by aleksanderEE** [sangria-graphql/sangria#506]
Now that the access to this repository has beed recovered, the temporary old repo - https://github.com/sangria-graphql-org/sangria/ - should be either deleted or archived with a README note redirecting here

**Comment by yanns** [comment]
There's already a note:

<img width="997" alt="Screenshot 2020-09-09 at 16 34 24" src="https://user-images.githubusercontent.com/51669/92612646-58731f80-f2ba-11ea-94d6-497a4990cda6.png">

Is it sufficient?
