### ISSUE TITLE
remove scala 2.11?

### ISSUE THREAD

**Issue by yanns** [sangria-graphql/sangria#523]
Currently, sangria is cross-compiled to scala 2.11, scala 2.12 and scala 2.13.

The support of scala 2.11 could be removed for the following benefits:
- the scala 2.11 builds are failing very often
- some libraries used as dependencies are not supporting scala 2.11 anymore. Ex: Parboiled: https://github.com/sangria-graphql/sangria/pull/520
- we could fix some warnings in the code

Before removing support for scala 2.11, I'd like to know if anyone is using this version.
Please comment.

**Comment by paulpdaniels** [comment]
I opposed this move in the past, but we _just_ moved off of 2.11 it so 🟢 . I think this is the trend of the industry as well, `cats`, `circe` and `monix`, have all dropped it so I think it is reasonable to make versions going forward require 2.12 and above.

**Comment by nickhudkins** [comment]
I'd love to see 2.11 support dropped, especially as we know Dotty is on the way, and this will mean even MORE burden to the maintenance of sangria, which is already hurting :(

**Comment by yanns** [comment]
On the negative part of supporting scala 2.11:
we are using a jvm 1.7 for scala 2.11, leading to some issues like: https://github.com/sangria-graphql/sangria-relay/pull/37

I therefore decide to drop support for scala 2.11 and to only support jvm >= 1.8.

**Comment by nickhudkins** [comment]
Done!
