### ISSUE TITLE
Load Schema from .graphql file

### ISSUE THREAD

**Issue by steinroe** [sangria-graphql/sangria#525]
Hi, 

I am a scala newbie, so please excuse my question, but it is possible to load the schema from a .graphql file / string instead of defining it directly in scala code?

Best
Philipp

**Comment by nickhudkins** [comment]
Hi @steinroe:

You most certainly can. The key is not Sangria specific, but reading the contents of the `.graphql` into memory as a string. (Line 1 below)

The second part is parsing it `QueryParser.parse(schemaAsString)` which gets you an AST.

Lastly, materializing the AST into an executable schema, `Schema.buildFromAst`.

Hope this helps!

```scala 
val schemaAsString = Source.fromFile(filename).getLines.mkString
val schema: Schema[_, _] = Schema.buildFromAst(
	QueryParser.parse(schemaAsString)
)

```
