### ISSUE TITLE
Recursive ObjectTypes

### ISSUE THREAD

**Issue by pasviegas** [sangria-graphql/sangria#54]
Hey, I am trying to have 2 ObjectTypes that are recursively linked.

A has a field with B type and B has a field with A type.

Is there any way to do this?

Thanks

**Comment by OlegIlyenko** [comment]
Sure. Fields of an `ObjectType` or `InterfaceType` can be a no-arg function. It is there to cover exactly this case. Here is a small example:

    case class A(b: B, name: String)
    case class B(a: A, size: Int)
  
    val AType: ObjectType[Unit, A] = ObjectType("A", () => fields[Unit, A](
      Field("name", StringType, resolve = _.value.name),
      Field("b", BType, resolve = _.value.b)))
  
    val BType: ObjectType[Unit, B] = ObjectType("B", () => fields[Unit, B](
      Field("size", IntType, resolve = _.value.size),
      Field("a", AType, resolve = _.value.a)))

**Comment by pasviegas** [comment]
Cool, thanks!

I had wrapped everything in OptionType and used lazy val for it, also worked, but I was hoping for a better alternative! Thanks a lot!

**Comment by OlegIlyenko** [comment]
Great, glad that it helped!
