### ISSUE TITLE
Return Ctx on Executor's execute method

### ISSUE THREAD

**Issue by giannoug** [sangria-graphql/sangria#556]
Maybe there is an alternative way, but I'm currectly trying to alter the HTTP request from a Sangria mutation in my Play Framework application. I have a mutation that changes a value and updates the current context. My goal is to add some HttpOnly cookies to the client based on some value in my Sangria context. I'm sure I break some spec and/or convention here.

Here's my current implementation:
```
Executor
  .execute(
    schema = schema,
    queryAst = queryAst,
    userContext = ctx,
    operationName = operation,
    variables = variables
  )
  .map(Ok(_))
  .recover {
    case error: QueryAnalysisError => BadRequest(error.resolveError)
    case error: ErrorWithResolver => InternalServerError(error.resolveError)
  }
```

This returns an HTTP 200 OK response with the value of the `PlayJsonResultMarshaller`, a simple `JsValue` that contains the JSON generated by Sangria and marshalled by Sangria's `PlayJsonResultMarshaller`. Ideally I would like to do something like this (wrote this out of my head, it might not compile correctly):
```
Executor
  .execute(
    schema = schema,
    queryAst = queryAst,
    userContext = ctx,
    operationName = operation,
    variables = variables
  )
  .map { case (ctx, response) => Ok(response).withCookies(Cookie("color", ctx.color))}
  .recover {
    case error: QueryAnalysisError => BadRequest(error.resolveError)
    case error: ErrorWithResolver => InternalServerError(error.resolveError)
  }
  ```

As you can see, the context is also returned so I can act based on a value contained in it. Maybe I need a custom marshaller? I can see that `execute` returns a `scheme.Result[Ctx, marshaller.Node]` 🤔

**Comment by paulpdaniels** [comment]
I've never used this myself but I believe if you use the `Extended` `ExecutionScheme` it returns the full query context instead of just the marshalled result  [source](https://github.com/sangria-graphql/sangria/blob/master/modules/core/src/main/scala/sangria/execution/ExecutionScheme.scala#L44)

**Comment by giannoug** [comment]
You are correct! There is also a relevant documentation page that I totally missed: https://sangria-graphql.github.io/learn/#alternative-execution-scheme

Got it working now, thanks a lot 👍
