### ISSUE TITLE
Implement ArgonautJsonSupport in order to integrate with argonaut

### ISSUE THREAD

**Issue by schrepfler** [sangria-graphql/sangria#59]
Argonout is a JSON scala library backed by scalaz

**Comment by OlegIlyenko** [comment]
At the moment I added support for most popular json libraries (to my knowledge). The plan is to separate every json integration in separate library (when I feel that the facade is more or less stable):

https://github.com/sangria-graphql/sangria/issues/38

At this stage I also would like to add support for additional JSON libraries (like argonaut and circle).

**Comment by OlegIlyenko** [comment]
FYI: this one is blocked by Argonaut 6.1 release which includes big decimal number support. (Probably will be come with #38)

**Comment by crispywalrus** [comment]
Argonaut 6.1 was released back in April, so what more is needed here?

See: 
http://search.maven.org/#artifactdetails%7Cio.argonaut%7Cargonaut_2.11%7C6.1%7Cjar

**Comment by OlegIlyenko** [comment]
Thanks for pointing this out! I was misled by the project's [homepage](http://argonaut.io/) which states:

> The current published version of argonaut is 6.0.4

**Comment by OlegIlyenko** [comment]
Integration library is now here: https://github.com/sangria-graphql/sangria-argonaut
