### ISSUE TITLE
Deferred, how to avoid N+1 queries

### ISSUE THREAD

**Issue by luisobo** [sangria-graphql/sangria#63]
Hi,

Loving sangria, it made it all the way to production so thanks for that!

I'm tryind to avoid a N+1 queries. My schema looks something like this:

```
type Query {
  articles(first: Int, after: String): ArticleConnection!
}

type Article {
  id: ID!
  comments(first: Int, after: String): CommentsConnection!
}

type Comment {
  content: String!
}
```

The problem happens when requesting multiple articles and their comments:

```
query articlesWithComments {
  articles {
    edges {
      node { 
        id
        comments {
          edges {
             node {
                 content
              }
            }
         }
       }
     }
   }
}
```

The execution goes like this:
1. 1 api call to request the page of articles, it returns 10, for instance
1.  10 api calls to retrieve the comments of each article

Ideally, I'd have an endpoint that will return the comments of N articles so step number two can be collapsed into one api call and returns a map of articleId -> Page[Comment]

I've been playing around with Defer and DeferredResolver but I can't get it to work with this case. The documentation covers the case you have a list of comment ids and you retrieve them all at once and not the other way around.

Any suggestions on how to implement this?

Again, thank you so much for sangria and thank you for your time.

**Comment by OlegIlyenko** [comment]
Wow, really glad to hear this! Thanks a lot for the kind words!

I think `Defer` still can be used in this case, but I need to understand the data model better. As far as I understood, in order to fulfill a GraphQL query you call some other (I would assume RESTful) API. Is it correct?

So that the first step (`articles` field resolve function) will make an HTTP request like this:

```json
GET http://some.other.service/articles
{
  "result": [
    {"id": 123, "name": "Foo"},
    {"id": 987, "name": "Bar"}
  ]
}
```

and then, in the second step (in `comments` field resolve function), you make additional HTTP requests for every article:

```json
GET http://some.other.service/comments?forArticleId=123
{
  "result": [
    {"content": "Comment 1"},
    {"content": "Comment two"}
  ]
}

GET http://some.other.service/comments?forArticleId=987
{
  "result": [
    {"content": "Some other comment"}
  ]
}
```

Have I understood it correctly? if yes, than I have one more question :) Can you also ask this service for comments from different articles in one request, something like: `http://some.other.service/comments?forArticleIds=123,987` or `http://some.other.service/comments?forArticleId=123&forArticleId=987`?

**Comment by luisobo** [comment]
You understood everything correctly and yes, it will be possible to retrieve the comments of multiple articles in one just as you described

**Comment by OlegIlyenko** [comment]
Great, thanks for the quick reply! Here is an example of how you can use `Deferred` in this case. Just to make the example complete, I would like to define some mock data first:

```scala
  case class Article(id: String, name: String)
  case class Comment(articleId: String, content: String)

  class ExternalService {
    def fetchArticles: List[Article] =
      List(Article("123", "Foo"), Article("987", "Bar"), Article("7364", "Baz"))

    def fetchComments(articleIds: List[String]): List[Comment] =
      articleIds flatMap {
        case "123" => List(Comment("123", "Comment 1"), Comment("123", "Comment two"))
        case "987" => List(Comment("987", "Some other comment"))
        case _ => Nil
      }
  }
```

`Deferred` and `DeferredResolver` implementation can look like this:

```scala
  case class CommentsDeferred(articleId: String) extends Deferred[Seq[Comment]]

  class CommentsResolver(service: ExternalService) extends DeferredResolver {
    def resolve(deferred: List[Deferred[Any]]) = {
      val articleIds = deferred map {case CommentsDeferred(id) => id}
      val comments = service.fetchComments(articleIds)
      val commentsByArticle = comments groupBy (_.articleId)

      articleIds map (id =>
        Future.successful(commentsByArticle get id getOrElse Nil))
    }
  }
```

Now we can define (simplified) schema that uses it:

```scala
  val CommentType = ObjectType("Comment", fields[Unit, Comment](
    Field("content", StringType, resolve = _.value.content)))

  val ArticleType = ObjectType("Article", fields[Unit, Article](
    Field("id", StringType, resolve = _.value.id),
    Field("comments", ListType(CommentType), resolve = ctx => CommentsDeferred(ctx.value.id))
  ))

  val QueryType = ObjectType("Query", fields[ExternalService, Unit](
    Field("articles", ListType(ArticleType), resolve = _.ctx.fetchArticles)))

  val schema = Schema(QueryType)
```

And finally the query:

```scala
val query = graphql"{articles {id comments {content}}}"

val service = new ExternalService
val resolver = new CommentsResolver(service)

Executor.execute(schema, query, userContext = service, deferredResolver = resolver)
```

This GraphQL query will cause only 2 calls of `ExternalService`: one for the list of articles and another one will fetch all of the comments for these articles. Result will look like this:

```json
{
  "data": {
    "articles": [{
      "id": "123",
      "comments": [{
        "content": "Comment 1"
      }, {
        "content": "Comment two"
      }]
    }, {
      "id": "987",
      "comments": [{
        "content": "Some other comment"
      }]
    }, {
      "id": "7364",
      "comments": []
    }]
  }
}
```

Does this solution help to avoid N+1 queries in your case?

**Comment by luisobo** [comment]
It works perfect, thank you so much!
