### ISSUE TITLE
Scala.js support

### ISSUE THREAD

**Issue by ngbinh** [sangria-graphql/sangria#64]
With circe supports Scala.js, I think it makes sense now.

**Comment by OlegIlyenko** [comment]
I would appreciate if you could describe the use-cases you have in mind for sangria scalajs support.

**Comment by chandu0101** [comment]
the only use case  i can think of is client library/dsl to write graphql/relay-graphql queries . and a tool which can generate scala case classes/models from schema.js/schema.json (it comes under tooling though) .

**Comment by ngbinh** [comment]
I think we can use GraphGL to define the app data schema. Then use Sangria as both backend and frontend to allow more efficient queries.

**Comment by OlegIlyenko** [comment]
Thanks for the quick replies! I doubt that scalajs version of sangria on the client side (as well as scala version on the client) will help in terms of performance, but I definitely see that can help with query validation and tooling and possibly with code generation.

At the moment there are no specific plans for scalajs support. But I may look at it later, when library and spec will become more stable and mature.

**Comment by ngbinh** [comment]
@OlegIlyenko Thanks!

**Comment by ngbinh** [comment]
Also, it wasn't in general too hard to write scala.js compatible Scala code (no reflection, no busy wait). The main challenge is in the dependencies and the build.

**Comment by sscarduzio** [comment]
no updates on this one?

**Comment by virtualirfan** [comment]
+1 on scalajs support.

**Comment by jonas** [comment]
My own experience from using Sangria with a Scala.js frontend is that it is fairly straightforward to validate queries in the backend's test suite by putting the GraphQL query strings and request helpers in the shared code. We only have "static" queries though, no relay-kind of composition.

I'd personally be interested in Scala.js support for generating efficient domain models from a GraphQL query using scala.meta, however, that is probably out of scope for this project.

**Comment by OlegIlyenko** [comment]
I agree, I also quite interested in exploring the client  code generation. And, indeed, it is out of scope for core project, but should be possible to implement as a separate lib/sbt plugin. I'm also looking closely on what apollo does with apollo-ios and android. Maybe we can reuse or get inspiration from their work (without overreliance on nodejs)

**Comment by OlegIlyenko** [comment]
Apollo team is already working on scala.js related projects: https://dev-blog.apollodata.com/scala-js-and-apollo-better-together-b066c6b09af4. It looks very promising!

I will close this issue for the moment being. Scala.js is relatively broad topic, so I would suggest to break this topic down to more narrowly focused issues as need arises.
