### ISSUE TITLE
[scala3] macro-visit

### ISSUE THREAD

**Issue by yanns** [sangria-graphql/sangria#649]
This library relies on macros and will need quite some work to port to scala 3.

And there is a circular dependency between this library and sangria. Maybe we should cut this circular dependency to ease the migration.

```
libraryDependencies ++= Seq(
          // macros
          "org.scala-lang" % "scala-reflect" % scalaVersion.value,
          // testing
          "org.scalatest" %% "scalatest" % "3.2.9" % Test,
          "org.sangria-graphql" %% "sangria" % "2.1.3" % Test
        )
```

**Comment by gzoller** [comment]
I’ll leave this here:  https://github.com/gzoller/scala-reflection
Built this for ScalaJack support for Scala3, since reflection went away.  It uses Scala3 macros and might help here.

**Comment by yanns** [comment]
Thanks for the info!
I've started a WIP PR to bootstrap the work on the macros: https://github.com/sangria-graphql/macro-visit/pull/82

**Comment by yanns** [comment]
https://github.com/sangria-graphql/macro-visit/pull/135

**Comment by yanns** [comment]
https://github.com/sangria-graphql/macro-visit/releases/tag/v0.2.0-RC1
