### ISSUE TITLE
[Feature Request] Ability to add directives

### ISSUE THREAD

**Issue by Yomanz** [sangria-graphql/sangria#671]
I can't see any way to create any directives within a schema.

I tried but I ran into the same issue that has been open for a while.

https://github.com/sangria-graphql/sangria/issues/467
Any help is greatly appreciated.

**Comment by xsoufiane** [comment]
I might help you here 🤔 there are two parts to consider while using a custom directive. The first part is the definition, for that you use sangria.schema.Directive, as can be seen [here](https://github.com/sangria-graphql/sangria-federated/blob/main/core/src/main/scala/sangria/federation/Directives.scala). The second part is to actually use the defined directive, and for that you need to use sangria.ast.Directive, [here](https://github.com/sangria-graphql/sangria-federated/blob/55787dc575bc36ddaa9dc251cc1d9e829f374472/example/review/src/main/scala/review/State.scala#L16).

**Comment by Yomanz** [comment]
> 
> 
> I might help you here 🤔 there are two parts to consider while using a custom directive. The first part is the definition, for that you use sangria.schema.Directive, as can be seen [here](https://github.com/sangria-graphql/sangria-federated/blob/main/core/src/main/scala/sangria/federation/Directives.scala). The second part is to actually use the defined directive, and for that you need to use sangria.ast.Directive, [here](https://github.com/sangria-graphql/sangria-federated/blob/55787dc575bc36ddaa9dc251cc1d9e829f374472/example/review/src/main/scala/review/State.scala#L16).

I tried this and it didn't seem to apply them to the schema sadly.

**Comment by yanns** [comment]
https://github.com/sangria-graphql/sangria/discussions/913

**Comment by yanns** [comment]
Fixed by https://github.com/sangria-graphql/sangria/pull/918
