### ISSUE TITLE
deriveInputObject not working for a case class which has an Enum 

### ISSUE THREAD

**Issue by abhishekvaidprophecy** [sangria-graphql/sangria#676]
Scala 2.12
Sangria version: 1.4.2

- I want to create an argument from a case class which has an Enum field. I'm using `deriveInputObject` macro on the case class to do this.
- I have other things mentioned in my implicit scopes. This ensures compilation succeeds.  
- My compilation succeeds and I can see definition being correct in `graphiql`. 
- The problem is that when I try to query, I'm unable to go through as I get this error: 

```
{
  "data": null,
  "errors": [
    {
      "message": "Argument 'dummyForTest' has invalid value: At path '/anEnumVal': error.expected.validenumvalue (line 3, column 24):\n  Dummy( dummyForTest: {v1:\"aString\", anEnumVal: AnEnumVal1} )\n                       ^",
      "path": [
        "Dummy"
      ],
      "locations": [
        {
          "line": 3,
          "column": 24
        }
      ]
    }
  ]
}
```

Here are a few screenshots to exactly show what is happening: 

<img width="1026" alt="Screenshot 2021-06-10 at 8 50 39 PM" src="https://user-images.githubusercontent.com/75244584/121551917-a7a6d600-ca2d-11eb-9be0-ec9eae468ce1.png">
<img width="1790" alt="Screenshot 2021-06-10 at 8 47 58 PM" src="https://user-images.githubusercontent.com/75244584/121551936-aa093000-ca2d-11eb-98ee-8aac45c59b03.png">
<img width="1083" alt="Screenshot 2021-06-10 at 8 38 14 PM" src="https://user-images.githubusercontent.com/75244584/121551947-ae354d80-ca2d-11eb-8fd0-3d922fc0fd22.png">

**Comment by yanns** [comment]
A guess:
the json structure expected by enumeratum.PlayJsonEnum does not fit with the json received from the GraphQL query.
If it's the case, you may have to modify the json in between.

**Comment by abhishekvaidprophecy** [comment]
It was an issue with Play Json not Sangria
