### ISSUE TITLE
BUG: Type resolution of abstract types relies on simple "instanceof" checks - ignores Generics

### ISSUE THREAD

**Issue by kroeberk** [sangria-graphql/sangria#679]
In my project I have two classes:

EntityWrapper[Course] and EntityWrapper[CourseState]

both implement the Node interface (of Sangria relay, but that doesn't matter, it applies to all interfaces.

Now if two types implement the same interface, he checks the "correct" type using this code in Schema.scala:64 in the class sealed trait AbstractType extends Type with Named

    def typeOf[Ctx](value: Any, schema: Schema[Ctx, _]): Option[ObjectType[Ctx, _]] =
      schema.possibleTypes
        .get(name)
        .flatMap(_.find(_.isInstanceOf(value)).asInstanceOf[Option[ObjectType[Ctx, _]]])

Now obviously both of my classes instanceOf[EntityWrapper] is true, so he concludes that any class that extends EntityWrapper is a node. 

The result is, that he wrongly returns the CourseState type when i directly query a node with the id of a Course. Obviously, no fields will resolve and you get empty results.

**Comment by yanns** [comment]
Yes, you need to create 2 different graphql types.
