### ISSUE TITLE
Support an EitherType in schema

### ISSUE THREAD

**Issue by crispywalrus** [sangria-graphql/sangria#71]
I built out a very limited form of this with an enum and a required field. it seems like a simple and basic addition to support the concept of Either in the core schema.

**Comment by OlegIlyenko** [comment]
GraphQL supports union types which are represented with `UnionType` in sangria. There are some examples of it's usage in the tests:

https://github.com/sangria-graphql/sangria/blob/master/src/test/scala/sangria/execution/UnionInterfaceSpec.scala#L26

Is it something that can cover your use-case?

**Comment by crispywalrus** [comment]
ah, nice. Yes, this will work. thanks
