### ISSUE TITLE
Return authorization error code.

### ISSUE THREAD

**Issue by jorkey** [sangria-graphql/sangria#710]
I am using OAuth for authorization.
I use Query Reducer  to initialize account info in the GraphQL context. Query Reducer performs an asynchronous query to the database by account name from access token.
The question is: What to do if the access token is incorrect, or is missing, so that the client can make a redirect to the login page.
Unfortunately GraphQL does not support error numbers, so HTTP is better suited for error handling. In this case, it would be logical to return HTTP Status Code 401.
How to do it?

**Comment by yanns** [comment]
We use something like https://sangria-graphql.github.io/learn/#middleware-based-auth
With an `ExceptionHandler`, we create an error response with an [error code in the extension](https://docs.commercetools.com/api/graphql#error-response-format).
Finally, we check the result json. Based on the error code, we change the HTTP status code.
