### ISSUE TITLE
Think about alternative ways of returning error 

### ISSUE THREAD

**Issue by OlegIlyenko** [sangria-graphql/sangria#72]
At the moment one need to trow an exception in order to signify an error (or fail future). Maybe there is a possibility to support `Try` or `Either` as a result of `resolve`. 

Related reference implementation PR: https://github.com/graphql/graphql-js/pull/178

**Comment by dlreeves** [comment]
Saw this talk about error handling in Scala. Not sure if it is overkill for this issue or not, but think it does present a few possibilities for error handling. https://www.parleys.com/tutorial/delimited-dependently-typed-monadic-checked-exceptions-scala-1

**Comment by OlegIlyenko** [comment]
Thanks for the idea! I think already use similar technique in [DeliveryScheme](https://github.com/sangria-graphql/sangria/blob/master/src/main/scala/sangria/parser/DeliveryScheme.scala). The thing about `resolve` is it's an inverse situation - it's the user code retiring either success or an error (instead of a library code). But let's see, maybe existing `Action`-based infrastructure (which is pretty flexible) will allow alternative mechanism for error reporting

**Comment by OlegIlyenko** [comment]
Indeed, I just looked at it and it was pretty straightforward to implement `TryValue`action which allows to return `Try` and a result of `resolve`.

**Comment by ostronom** [comment]
Is it possible, that Executor swallows exceptions in Futures? I'm seeing this situation right now. The onFailure block on my future (which is returned as resolver) reports that there was an error. But when i remove it and try to recover on Executor -- nothing seems to be triggered.

**Comment by OlegIlyenko** [comment]
@ostronom The errors in the `resolve` functions are added in the `errors` array of the response. GraphQL tolerates these kind of errors and still considers the execution to be successful even in presence of errors. That's why the `Future`, which is returned from `Executor.execute`, is successful. If you would like to handle exceptions returned from a `resolve function, then I would suggest to define a [custom `ExeptionHandler`](http://sangria-graphql.org/learn/#custom-exceptionhandler).
