### ISSUE TITLE
Handling a single exception in a batch of otherwise successful queries 

### ISSUE THREAD

**Issue by ferestrepo** [sangria-graphql/sangria#732]
New to Sangria, so apologies if this is a silly question: 

The default behavior (as observed in the playground implementation) is that, when making multiple queries, if a single query fails while the others succeed, the entire operation is considered a failure and only the errors are returned (null data).

In our application, we've defined a custom exception handler, but need the ability to return the results of the successful queries along with the errors. Is there a way to achieve this behavior in the Sangria Executor? 

Thank you!

**Comment by ferestrepo** [comment]
To add a bit more color to this, It looks like this behavior occurs in the Sangria Playground implementation (https://sangria-play-example.herokuapp.com/playground) as well. 

Input: 
```
query MyTest {
  hero {
    name
    id
  }
  droid(id:"20011") {
   name
  } 
}
```

Output: 
```
{
  "data": null,
  "errors": [
    {
      "message": "Internal server error",
      "path": [
        "droid"
      ],
      "locations": [
        {
          "line": 6,
          "column": 3
        }
      ]
    }
  ]
}
```

But the GQL spec (http://spec.graphql.org/June2018/#sec-Query, http://spec.graphql.org/June2018/#sec-Errors) leads me to believe that the response should have both the `data` (for the `hero` piece of the query that succeeds) and `error` entries defined.

**Comment by yanns** [comment]
it depends if a field is mandatory or not.
For example, if `hero` can be resolved, but if `droid` is mandatory for the query result, then it's not possible to return `droid: null`, and the whole `data` must be `null`.
