### ISSUE TITLE
Removing the path and location values from Exception

### ISSUE THREAD

**Issue by abhigp27** [sangria-graphql/sangria#785]
Is there a way to remove the path and location values from exception. Only interested in error message and extensions.
A little further, is it possible to overwrite the whole structure and replace with only, errorCode, Description and a custom message.

```
{
  "data": null,
  "errors": [
    {
      "message": "Internal server error",
      "path": [
        "droid"
      ],
      "locations": [
        {
          "line": 6,
          "column": 3
        }
      ]
    }
  ]
}
```

**Comment by yanns** [comment]
I don't think there's a direct way.

You can use an `ExceptionHandler` to handle your errors, possibly with `HandledException`.
And you can always transform the result json to remove the fields you don't want before sending it over the wire.
