### ISSUE TITLE
remove the `Schema.build`⁎ methods

### ISSUE THREAD

**Issue by performantdata** [sangria-graphql/sangria#813]
In the `schema.Schema` object, there are 8 methods having names starting with `build`, whose presence creates a dependency from `Schema` to the materializers and builders. Their implementations are simple. They should be deprecated in 2.x.

The remaining question is whether to
1. remove them in 3.0, saying to call the materializer methods directly; or
1. copy the methods in 2.x to another object that's closer to the materializers.

**Comment by yanns** [comment]
Could you explain the motivation of such a change?

**Comment by performantdata** [comment]
Same as https://github.com/sangria-graphql/sangria/issues/809#issuecomment-986940264

I think it'll look like this: ![](https://raw.githubusercontent.com/gist/performantdata/69267dc937323380efc8c3608047e930/raw/db5465439f9c09b55610d0c06fa0295d122084a3/sangria.svg)

**Comment by performantdata** [comment]
This issue is replaced by #823.
