### ISSUE TITLE
Conditional scheme fields / api versioning

### ISSUE THREAD

**Issue by fedotxxl** [sangria-graphql/sangria#834]
Hello

Is it possible to define conditional scheme fields? 

E.g. clients passes header `X-API-VERSION: 2.0`. In this case, we will ad extra / changed field. Otherwise previous field version will be used

**Comment by yanns** [comment]
You can define different schemas, and your implementation can choose which one to use based on this header if you want.

You can also define one main schema, and another one by extending the first one.
