### ISSUE TITLE
Error behavior when `name` argument to ObjectType constructor contains a space

### ISSUE THREAD

**Issue by vreuter** [sangria-graphql/sangria#938]
When writing a new declaration of an `ObjectType`, I'd passed a value containing a space as the argument to the `name` parameter. While the source code itself compiled fine, the associated tests could not run. Specifically, in `sbt`, running `test` yielded an exception initialization error: `java.lang.ExceptionInInitializationError`. Is this a known bug, or an intended behavior? Just raising the question here to clarify and to perhaps help anyone facing a similar error.

**Comment by yanns** [comment]
I don't think that the graphql specs allows name to contain spaces: http://spec.graphql.org/October2021/#Name

**Comment by vreuter** [comment]
Indeed, thanks @yanns ! I'm relatively new to Sangria and not familiar with the implementation. Would it be possible to get a more informative error when this programmer error is made? In the end, it was fixed by intuiting (absent the knowledge of the restriction from GraphQL) the prohibition on space in the `name`, but I'm curious if it'd be feasible to get a message / exception type that would make the root cause more evident. Regardless, thanks for your reply!

**Comment by yanns** [comment]
This is the error message I have:
```
[info]   sangria.schema.SchemaValidationException: Schema does not pass validation. Violations:
[info] 
[info] Object type name 'DiscountedProductPrice Value' is invalid. Valid names must satisfy following regex: /^[_a-zA-Z][_a-zA-Z0-9]*$/.
[info]   at sangria.schema.SchemaValidationRule$.validateWithException(SchemaValidationRule.scala:54)
[info]   at sangria.schema.Schema.<init>(Schema.scala:1537)
```
It's already quite clear no?

**Comment by vreuter** [comment]
Hmm, I got something that did indeed compile (i.e. running `sbt compile` succeeded), but then when doing variants of `sbt test`, I got simply `java.lang.ExceptionInInitializationError` with no / minimal message. I can try to reproduce, but the absence of the more informative error message could be linked to the fact that the problematic declaration may've been masked by an object type that was identical at the type level, and indeed identical in all aspects except for the argument passed to the `name` parameter.

**Comment by yanns** [comment]
I guess that the error message is swallowed somewhere.
The error should happen on first access to your schema like:
```
object Schema {
  val mySchema = ...
}
```
Later in the test:
```
class MyTest {
  "the schema" should {
    "be initialize" in {
      assert(Some(Schema.mySchema).isDefined)
    }
  }
}
```
